### ISSUE TITLE
Optional select fields

### ISSUE THREAD

**Issue by chrisvanpatten** [mgibbs189/custom-field-suite#133]
Quick idea:

If a select field is optional, you should automatically insert an `<option>` at the top of the list  ("Select a value" or something) so users can choose not to save data in a field. CFS would just internally interpret this field as "unselected" or something like that and remove the saved values.

Thanks!

**Comment by mgibbs189** [comment]
I can't remember when it was added, but this looks to have been resolved. There's a special {empty} tag that can be used for the default choice, e.g.

`{empty} : Select a value`

**Comment by chrisvanpatten** [comment]
:rocket:
