### ISSUE TITLE
Feature Request: Conditional Fields

### ISSUE THREAD

**Issue by voltronik** [mgibbs189/custom-field-suite#158]
Would love to see this. Currently I have to put anything conditional in a note above the input for the user.

I think it would work similar to a loop. A conditional field would be a small group of fields that would be dependant on a field above being true/false, filled-out, etc.

**Comment by jayharland** [comment]
This would be great

**Comment by mgibbs189** [comment]
Closing. There are no plans to add conditional logic in the near-term.

Our top priority is to keep CFS stable and lightweight. Conditional logic would add code bloat, which seems unnecessary given that this isn't an often-requested feature.

**Comment by Santana1053** [comment]
Is there any update on this? I'm working on a project and it would be sweet if I could get this option. Even if you don't want to put it in the core, it would make one hell of an addon
