### ISSUE TITLE
Position before the_content editor

### ISSUE THREAD

**Issue by chrisvanpatten** [mgibbs189/custom-field-suite#177]
I'd love to be able to place fields above the primary content editor on an edit page. I believe there's a hook up there now that would enable that (maybe added in 3.6 or 3.7?)

Not a huge issue. Just one of those "would be nice" types of things!

**Comment by voltronik** [comment]
+1

**Comment by mgibbs189** [comment]
There's an `edit_form_after_title` hook, but no `do_meta_boxes` above the editor. To get this to work, we'd have to manually trigger do_meta_boxes within edit_form_after_title. Not impossible, but I'm wondering if it's worth the extra code to get this added.

**Comment by robneu** [comment]
I'd +1 this as well. Even when the editor is hidden, so many other plugins WP SEO for one, add metaboxes that wind up pushing the field groups way down in the priority listing. When new users try to edit a page with a field group for the first time they sometimes have a hard time finding it.

**Comment by mgibbs189** [comment]
I think the bigger issue here is that there's simply too much stuff on the edit screen, overwhelming users.

Related: https://calderawp.com/downloads/caldera-metabox-organizer/

**Comment by robneu** [comment]
That's accurate, but there's also not really anything we can do about it right now. When a page is controlled exclusively by CFS field groups, it really doesn't make sense for them to be displayed anywhere other than directly after the post title/permalink section.

Yoast is installed on the vast majority of sites that I've worked on and even when no other metabox-creating plugins are installed on the site its giant metabox pushes the CFS fields down the page making things pretty confusing for users.

I suppose there's ways to work around this by doing something similar to what that plugin does, but IMO it would be a lot easier to just be able to hook CFS earlier than everything else.

If you'd be willing to merge it, I can make a PR to get this working.
