### ISSUE TITLE
save() should return FALSE on error

### ISSUE THREAD

**Issue by Stock-Webdesign** [mgibbs189/custom-field-suite#187]
save() should not break the whole site. When it cannot do the saving (for whatever reason), it should return FALSE.

Right now it's very difficult to use CFS in a safe way.

**Comment by Stock-Webdesign** [comment]
Hmm - did you understand my point? The function MUST NOT break everything on error. They should just return FALSE in that case.

On success they should return TRUE or the actual value like: 1, 0, "", "foo".

Don't you agree on that? It's a big NoGo that your methods break everything on error!

Thanks for awesome work anyway. I use it a lot.

**Comment by chrisvanpatten** [comment]
You can't rely on people to be type checking the return values properly. While it's true that `0 !== false`, it's also true that `0 == false`. You might be type-checking properly, but many users _won't_ be, and it could break their installs.

**Comment by Stock-Webdesign** [comment]
For me it's more important, that the site does not break, than that bad developers get wrong results. But OK :-) matter of taste, I guess.

**Comment by mgibbs189** [comment]
Hey @stock-webdesign,

save() currently returns the post ID on success. This is very important when using save() to add new posts.

As for failure, I think you're right in that there's room for improvement. I think it should return boolean false, and also log the actual error somewhere.

When you say it breaks your site, is it actually triggering a PHP error? If so, could you show me a stack trace?

@chrisvanpatten yeah, the good news though is that the user could use == for comparison since post ID of 0 won't ever exist.

Thanks, and apologies about closing the ticket prematurely. I was on gibhub way too late :)

**Comment by Stock-Webdesign** [comment]
Cool.

I get a problem when a field just does not exists. It's something with "pre_save()". Right now, I must try to get the field first to make sure it exists.

**Comment by chrisvanpatten** [comment]
What about returning a WP_Error instead of false? You can check the return value with is_wp_error() ?

**Comment by Stock-Webdesign** [comment]
Also cool. This way you could add some infos later.

**Comment by mgibbs189** [comment]
@chrisvanpatten good suggestion! We could either return a WP_Error directly on failure, or return `FALSE` and store the WP_Error in another CFS variable. Thoughts? I'm trying to think aloud as to which would be easier / more convenient for users.

Also, it looks like there are a few things I could do to prevent errors to begin with (within the API class itself).

**Comment by Stock-Webdesign** [comment]
"return FALSE and store the WP_Error in another CFS variable"

I like that the best, because FALSE is all I need normally and is easier to check.

**Comment by chrisvanpatten** [comment]
I think that seems unwieldy but it's not my call at the end of the day!

**Comment by chrisvanpatten** [comment]
To elaborate - instead of just looking for false, you can just check the return with `is_wp_error()`, which is effectively the same thing. It's more consistent with how other functions operate and keeps you from needing to look in two places to get all the information you need.

**Comment by Stock-Webdesign** [comment]
"=== false" is much easier than remembering the wp-function. But I like that there is a place where I could get the info, when developing.

**Comment by mgibbs189** [comment]
So the two options are either:

```php
$post_id = CFS()->save( $field_data, $post_data );
if ( ! is_wp_error( $post_id ) ) {
    // do stuff
}
```

or

```php
$post_id = CFS()->save( $field_data, $post_data );
if ( false !== $post_id ) {
    // do stuff
}
```

At this point, I'm leaning towards @chrisvanpatten's is_wp_error() approach. It does seem a little cleaner...

@Stock-Webdesign you mentioned something about `pre_save()` before, is there any chance you could provide some more information? I'm trying to figure out the underlying cause of that issue, in hopes that it would be prevented.

**Comment by Stock-Webdesign** [comment]
Just try to save to a field that does not exist.

Less experienced developers will not check for is_wp_error() but OK, they would not check for "!==" either. With #1 the site breaks on error (cannot use object ...) and with #2 the script would continue, but with unwanted behaviour.

I would still prefer #2 because breaking the site is the worst that can happen IMHO.

**Comment by Stock-Webdesign** [comment]
On the other hand an error can be hard to notice, if the script does not break.

**Comment by Stock-Webdesign** [comment]
But saving a value to a field that does not exist should not be an error. That should be a valid call that just cannot be executed and therefore returns FALSE IMO. Then this would be fine:

$post_id = CFS()->save( $field_data, $post_data );
if ( $post_id ) {
    // do stuff
}

I really like that. That's also what most developers write, I guess.

**Comment by mgibbs189** [comment]
Good news, I found the error that was causing save() to crash on missing fields.

Now, CFS will skip missing fields and continue gracefully.

**Comment by Stock-Webdesign** [comment]
Cool.

I would like to get the number of values that have been saved. I know the post-id anyway (currently the return value), but I would like to check if all fields have been saved.

**Comment by mgibbs189** [comment]
Yep, in the next version, you'll be able to use `CFS()->api->saved_fields`:

```php
$saved_field_ids = CFS()->api->saved_fields;
echo count( $saved_field_ids );
```

**Comment by Stock-Webdesign** [comment]
Thanks for good work :-)

**Comment by mgibbs189** [comment]
Closing, see 331c987

**Comment by Stock-Webdesign** [comment]
Can you return the number of values that have been saved directly, so this would be possible: 

<pre>
$saved_fields_count = CFS()->save( $field_data, $post_data );
if ( $saved_fields_count == count( $post_data ) ) {
    // do stuff
}
</pre>

or is it too much chaos? I think noone should get a problem unless he checked for the exact post id, which does not make much sense to me:

<pre>
$post_id = CFS()->save( $field_data, $post_data );
if ( $post_id == $post_data['ID'] ) {
    // do stuff
}
</pre>

Most developers have written the simple code anyway, I guess and that would still work:

<pre>
$post_id = CFS()->save( $field_data, $post_data );
if ( $post_id ) {
    // do stuff
}
</pre>

**Comment by mgibbs189** [comment]
I'm afraid not, as that would destroy backwards-compatibility. Users expect this method to return a post ID on success.
