### ISSUE TITLE
Adding a "OR" option for placement rules

### ISSUE THREAD

**Issue by christopherdro** [mgibbs189/custom-field-suite#214]
Maybe for the next release you can implement a "OR" option for selecting placement rules. Currently, If I set it to a certain post type then try to add it to the certain page, it will only show on the page.

**Comment by voltronik** [comment]
+1

**Comment by sebdesign** [comment]
What happened to this? That would be a very nice feature.

I would like to place a field group to a custom _Post Type_ **OR** a _Page Template_.

Now I have to set Post Type _equals to_ `page` and `post_type`, and set Page Template _is not_ `EVERY page template except the one(s) I need`.

And each time i'm creating a page template, I have to add it to this list to exclude it, which is counter-productive.
