### ISSUE TITLE
Data import / export

### ISSUE THREAD

**Issue by mgibbs189** [mgibbs189/custom-field-suite#218]
I'm looking for ideas on making the **content** import / export process easier. Currently, it's difficult because the **cfs_values** table adds an extra layer of complexity.

Ideas so far:

(a) Add hooks to the WP Importer / Exporter. On Export, attach a serialized array of cfs_values data to each post as postmeta. On Import, check for the postmeta and import if necessary.

**Comment by tiddydl** [comment]
I'm really interested in this feature, is anyone working on it?

I view loop post meta, for example, are imported with same name but in different rows, with the same order than they are in the loop. 
I think an option (not the best, but easy) is to insert a post meta row in the post each time a loop finishes (I haven't seen CFS code, but appareantly is posible).
Then can be added a new tab into the plugin admin page for choosing posts to parse.
In this parse you compare the post metas with the CFS structure for that page.

With this way you haven't to hook Wordpress Importer, and the process to import data would be:
1. Import CFS structure (as usual).
2. Import posts (as usual).
3. Parse posts.

What do you think? If you think there is a good way I work on it.

**Comment by tiddydl** [comment]
Forget the end-loop post meta, is better (like @mgibbs189 says on first post) to create one post meta with the CFS values serialized each time you save the post. Now I use this way to share CFS data between sites on Wordpress multisite.
Is anyone working on this feature?

**Comment by mgibbs189** [comment]
Closing this (for now)... there's a new Synchronize add-on that handles the import process.
