### ISSUE TITLE
WYSIWYG breaks when you move metabox

### ISSUE THREAD

**Issue by sddevstudio** [mgibbs189/custom-field-suite#223]
I noticed that if you have a WYSIWYG field and you move the metabox which it is in, the WYSIWYG is no longer responsive. If you typed something before it still seems to save the content if you save it.

**Comment by sddevstudio** [comment]
Hi Matt,
I had a chance to finally do a little more digging on this issue. It looks like you have the fix in place to refresh the tinyMCE, but it doesn't look like the sortable start/stop you are hooking is triggering. Below I have provided the code that I'm currently using to refresh.

In file: /includes/fields/wysiwyg.php at line 156 (ver:2.4), I have changed it to below: 
    $('.meta-box-sortables').on( "sortstart", function( event, ui ) {
    	tinyMCE.settings.wpautop = false;
    	tinyMCE.settings.resize = 'vertical';
    	$(this).find('.wysiwyg').each(function() {
    		tinyMCE.execCommand('mceRemoveEditor', false, $(this).attr('id'));
    	});
    });
    
    $('.meta-box-sortables').on( "sortstop", function( event, ui ) {
    	$(this).find('.wysiwyg').each(function() {
    		tinyMCE.execCommand('mceAddEditor', false, $(this).attr('id'));
    	});
    	tinyMCE.settings.wpautop = wpautop;
    	tinyMCE.settings.resize = resize;
    });

**Comment by mgibbs189** [comment]
Does that code work for wysiwyg fields within loops?

**Comment by sddevstudio** [comment]
Yes it does, just tested it. Works with newly added and moved around in the loop and the parent metabox.

I didn't realize that was in there to handle the re-arrange ment of the looped wysiwyg.

**Comment by mgibbs189** [comment]
Thanks again for reporting!
