### ISSUE TITLE
Placement rule ID remains attached although Post/Page dosn't exist

### ISSUE THREAD

**Issue by christopherdro** [mgibbs189/custom-field-suite#236]
If you have a field group attached to a certain page and happen to delete the page before removing the placement rule you have no way of removing that ID from the placement rules.

Clearing the placement rules is important when using CFS options screens since that relies on the field group not having any placement rules attached to it.

Hope this makes sense.

**Comment by mgibbs189** [comment]
This makes sense, but it can get pretty complicated.

Let's say you have a field group attached to 1 specific page. If the page gets deleted and we *automatically* update the placement rules, the rule for "Post IDs" would be empty. CFS would interpret this as "show for all posts", which isn't what you'd be expecting...

I think the best solution would be to show the post ID within the placement rules box, even for deleted posts. Know what I mean?
