### ISSUE TITLE
Issue when click on "Preview Changes" 

### ISSUE THREAD

**Issue by dipu-at-imaginea-rpx** [mgibbs189/custom-field-suite#239]
All,

I think I found an issue with custom-field-suite when user trying to see preview of the changes. Kindly follow the steps below and share your thoughts.

1) Go to edit screen of a post.

2) Modify main content and custom field data(those are created using custom-field-suite).

3) Click on "Preview Changes"

4) Go to post listing screen without saving it.

5) Then go to edit screen of same post there we modified content(but not saved), check the main content and data in custom fields.

Actual Result

1) Old content is appearing in main content area

2) Modified content appearing in custom fields.

Expected Result

Old content should appear in both main content and custom fields.

I hope plugin save the content in meta table while we click on " Preview Changes".

Please share your thoughts

Thank you
Dipu Ratheesan

**Comment by mgibbs189** [comment]
CFS does not store post revisions by default. If you're using CFS 2.4+, you can enable it manually by adding the following into your functions.php:

`define( 'CFS_REVISIONS', true );`
