### ISSUE TITLE
Add option to specify datepicker format

### ISSUE THREAD

**Issue by christopherdro** [mgibbs189/custom-field-suite#240]
Build out option to specify datepicker format.

```
format: 'mm/dd/yyyy',

```
I can also help get this working but there is no settings/options screen for CFS so I'm not sure how you would want to move forward with it. 
Having to specify the format every time you add a field seems to redundant so maybe a settings page is best?

Thanks

**Comment by mgibbs189** [comment]
I agree that we should support front-end display formatting, but all dates should still be stored in `YYYY-MM-DD` format in the database.

**Comment by mgibbs189** [comment]
I'm putting this issue on ice for now. The date picker library we're using, Bootstrap Datepicker, doesn't currently support custom display formats. Once it's implemented, we'll roll it into CFS.

**Comment by chrisvanpatten** [comment]
See eternicode/bootstrap-datepicker#1338

**Comment by mgibbs189** [comment]
@chrisvanpatten Yep, I added a comment there a few days back :)

**Comment by chrisvanpatten** [comment]
Yeah I saw, sorry should have clarified that was more of a "for future reference for the random people of the internet" comment
