### ISSUE TITLE
Tab groups in Edit Field Group screen have no UI feedback

### ISSUE THREAD

**Issue by su** [mgibbs189/custom-field-suite#244]
Once you figure out how the tab field works(see #243), it's pretty much obvious that whatever is between there and the next tab field is the "group," but it would be good for clarity if this adopted the indented display that Loop groups do, eg: 
![loop-nested-fields](https://cloud.githubusercontent.com/assets/42981/5957607/1f726ffe-a781-11e4-9406-6182b5dde631.png)

…though maybe using a different color? (I quickly tried nesting some tabs in a loop, and it seemed to kinda work though the interface wasn't too happy about it, so not sure if that's actually a supported scenario.)

**Comment by mgibbs189** [comment]
Thanks. Yes, it is somewhat confusing, but I don't want to make it double-confusing by having 2-separate causes of indented fields. Will need to think more about this..

**Comment by chrisvanpatten** [comment]
FWIW I also found this initially confusing. I think if it's a different colour, the indentation wouldn't be too much of a stretch.

I'm partially tempted to put together a PR for this and figure out a way to run some user tests...

**Comment by mgibbs189** [comment]
Closing in favor of #250

**Comment by chrisvanpatten** [comment]
@mgibbs189 closed in favour of #250, but #250 was closed two days ago? :P

**Comment by mgibbs189** [comment]
Damnit, I closed the wrong one FAIL :whale:
