### ISSUE TITLE
Clarify License

### ISSUE THREAD

**Issue by o1y** [mgibbs189/custom-field-suite#247]
Hey Matt,

I wasn't able to locate a license for you plugin. Is it distributed under the GPL? :)

Thanks!
Oliver

**Comment by chrisvanpatten** [comment]
[The license is specified as GPLv2 in the readme.](https://github.com/mgibbs189/custom-field-suite/blob/master/readme.txt#L8)

Might be worth including a license file though, and I think you can also mention the license in the plugin metadata in the opening PHP comment.

**Comment by chrisvanpatten** [comment]
[There's also a guide to using the GPL license at the GNU website](https://www.gnu.org/licenses/gpl-howto.html), which suggests including a full copy of the GPL license.

It _also_ suggests including a shorter copyright notice in each source file, but I'm not sure how necessary that is in practice. For what it's worth, most of the WordPress core files don't include the notice.

**Comment by mgibbs189** [comment]
Added license.txt to plugin folder. Closing.
