### ISSUE TITLE
Markdown Support for Textarea

### ISSUE THREAD

**Issue by robneu** [mgibbs189/custom-field-suite#249]
This would be a pretty neat feature and using something like https://github.com/erusev/parsedown would probably be pretty simple to add. Any thoughts? Would a PR to add this be out of the question? Better suited to an add-on?

**Comment by chrisvanpatten** [comment]
I think this would be best as an add-on as a separate field type, or done via a filter on the field's data. Either way, not sure it makes sense for CFS core.

**Comment by robneu** [comment]
That seems reasonable to me. I'll code up an add-on for it sometime this week.

**Comment by chrisvanpatten** [comment]
Cool! Looking forward to trying it out!

**Comment by robneu** [comment]
Here it is! https://github.com/robneu/cfs-markdown

**Comment by mgibbs189** [comment]
I'll add it to the Add-ons page if that's OK with you. If so, did you have a logo preference, or is the following OK: https://www.iconfinder.com/icons/298823/markdown_icon#size=128

**Comment by robneu** [comment]
That's fine with me! Icon looks good too. :+1:

**Comment by mgibbs189** [comment]
All set
