### ISSUE TITLE
Make moving rows in a loop field possible w/ only keyboard

### ISSUE THREAD

**Issue by chrisvanpatten** [mgibbs189/custom-field-suite#251]
This is one of those things that I'd like to tackle next time I have free time :)

Right now, loop fields aren't super accessible. You can't use the keyboard tabindex to expand/collapse or delete a field, and can only access the fields inside a loop element if it's already expanded.

I'd like to figure out a way to change that, so it's fully keyboard-navigable (sans re-ordering, although I even have ideas on how that could be accomplished... a bit more involved though).

**Comment by mgibbs189** [comment]
:+1:    :)

**Comment by mgibbs189** [comment]
5 months later, this still seems really complicated ;)

**Comment by chrisvanpatten** [comment]
Definitely complicated, but I have a few ideas.

My main flow idea:

#### Low-hanging fruit:
Add the open/close and delete links to the tabindex, so you can tab through them and activate them (this should be relatively easy and I can probably file a PR for it).

#### More complex:
Add a "keyboard mode" which is triggered by a shortcut (e.g. ctrl+alt+X or something), which allows you to tab between the loop elements to select them, and use up/down arrows to shift them.

**Comment by mgibbs189** [comment]
@chrisvanpatten I like the idea. Let's plan on addressing this right after 2.5 is release.

I feel like this could be one of those deceivingly-complex features, such as when new loop rows are added and when items are dragged around, etc.

**Comment by chrisvanpatten** [comment]
Shouldn't be a problem with the low-hanging fruit component, via browser-native tabindex... tabindex should just follow the current state of the DOM.

The other feature could get definitely get messy very quickly... much bigger challenge there.

**Comment by chrisvanpatten** [comment]
I've changed the name of the issue to reflect a more specific scope of what still needs to be done!

**Comment by mgibbs189** [comment]
@chrisvanpatten I'm closing this one for now. Gonna focus on some of the higher priority requests, time permitting
