### ISSUE TITLE
Unicode in field export/import

### ISSUE THREAD

**Issue by chrisvanpatten** [mgibbs189/custom-field-suite#253]
I have a set of fields; one of them is a multi-select list of countries.

I exported this to JSON (via the built-in exporter) and re-imported it, and noticed that any countries with diacritics in their names were not imported properly.

In the JSON, they look like this (excerpted, obviously):
```json
"C\u00f4te d\u2019Ivoire":"C\u00f4te d\u2019Ivoire",
```

When imported, they look like this:
![add_new_review_ _torrentfreak_ _wordpress](https://cloud.githubusercontent.com/assets/1231306/6557952/4cfd3cb2-c679-11e4-9f27-2a6602bf6ce6.png)

This is due to `stripslashes` getting [run on import](https://github.com/mgibbs189/custom-field-suite/blob/a6e4b475aa6df0e510562c7894bd17027bbfc6fb/cfs.php#L420).

**Comment by mgibbs189** [comment]
Hey @chrisvanpatten any ideas what that original encoding is? I haven't seen stripslashes() doing that for UTF-8 strings before, maybe that's UTF-16 or something similar?

**Comment by chrisvanpatten** [comment]
Let me figure out which project it was so I can track it down :)

**Comment by mgibbs189** [comment]
:+1:

**Comment by mgibbs189** [comment]
Punting this to sometime after 2.5 (maybe 2.5.1 or something).

**Comment by mgibbs189** [comment]
@chrisvanpatten I haven't been able to duplicate the issue. Screencast: http://d.pr/v/1164c

I'm closing for now. Please re-open if you can provide any more information or scenarios.

**Comment by chrisvanpatten** [comment]
I did a bit of research and I'm now 90% sure it was a database problem, not a CFS problem. I'm going to re-run a few tests and let you know definitively.
