### ISSUE TITLE
SVN tags on WordPress.org

### ISSUE THREAD

**Issue by chrisvanpatten** [mgibbs189/custom-field-suite#254]
For some reason, all the [SVN tags on WordPress.org have disappeared](http://plugins.svn.wordpress.org/custom-field-suite/tags/), leaving only [trunk](http://plugins.svn.wordpress.org/custom-field-suite/trunk/), which means that CFS can't be installed/updated properly through Composer and [wpackagist](http://wpackagist.org/). Was this intentional or a random bug?

**Comment by mgibbs189** [comment]
This was intentional. I've been tagging solely on GitHub for a while now (the only tags on WP.org were very old versions, before I removed them).

I'm open to suggestions though -- since CFS trunk is treated as the latest stable version, is there any reason not to use dev-trunk with packagist?

**Comment by chrisvanpatten** [comment]
I like being able to designate which version gets used so I can revert to older versions, but there's another way around it too... will submit a PR in a moment...

**Comment by chrisvanpatten** [comment]
Fixed with df346c76db85043f2637e074d46bcd207564b810!

**Comment by chrisvanpatten** [comment]
(Thanks, @mgibbs189!)

**Comment by chrisvanpatten** [comment]
FWIW I've noticed that now dev-trunk no longer works when using WPackagist. I can't get my copy of CFS on a particular site to update to 2.4.2. This could be a problem on their end but I haven't done too much research yet - just wanted to point it out here.
