### ISSUE TITLE
Getting fields in JSON for REST API

### ISSUE THREAD

**Issue by colinhowells** [mgibbs189/custom-field-suite#261]
Using the REST API (https://github.com/WP-API/WP-API) along with CFS.

I'm stuck on getting fields into the JSON response:

```php
function get_recipe_in_json( $post_response, $post, $context ) {
	
	// ensure global post is correctly set
    $old_post = $GLOBALS['post'];
    $GLOBALS['post'] = (object)$post;

    $post_response['recipe'] = array_merge( $post_response['recipe'], CFS()->get(false,$post['ID'],array('format' => 'raw')) );
    
    // reset global post to its old value
    $GLOBALS['post'] = $old_post;
    return $post_response;
    
}
if ( function_exists('CFS') ) {
	add_filter( 'json_prepare_post', 'get_recipe_in_json', 10, 3 );
}
```

A simple CFS()->get(); doesn't seem to do the trick, so if anyone can see where I've gone wrong advice is appreciated!

**Comment by mgibbs189** [comment]
I'm not too familiar with WP-API, but a couple things stick out:

1. array_merge won't work if the recipe key doesn't exist already
2. the `$GLOBALS` code seems unnecessary(?)
3. The CFS() function may not have loaded at the point you're checking for it

```php
function get_recipe_in_json( $post_response, $post, $context ) {
    if ( function_exists( 'CFS' ) ) {
        $post_response['recipe'] = CFS()->get( false, $post['ID'], array( 'format' => 'raw' ) );
    }
    return $post_response;

}
add_filter( 'json_prepare_post', 'get_recipe_in_json', 10, 3 );
```

**Comment by chrisvanpatten** [comment]
For what it's worth, I have some custom WP-API integrations that use CFS at some point in the process (none are direct like this though) and I had to wrap my filter hook in the `plugins_loaded` action:

```php
add_action( 'plugins_loaded', function() {
    add_filter( 'json_prepare_post', 'my_custom_json' );
} );
```

**Comment by colinhowells** [comment]
All right – after messing about with variations on all suggestions, this one was successful; I hope this helps someone out:

```php
function get_recipe_in_json( $post_response, $post, $context ) {
    $post_response['recipe'] = CFS()->get( false, $post['ID'], array( 'format' => 'raw' ) );
    return $post_response;

}
add_filter( 'json_prepare_post', 'get_recipe_in_json', 10, 3 );
```

Any check for CFS existing, or putting the filter behind the plugins_loaded action, would fail.

In answer to the question about $GLOBALS, I ran into an issue earlier where another json_prepare_post would consistently grab the *latest* post, instead of the one I needed information about – including that function here so you can see what I needed to do; it has nothing to do with CFS, but it might be useful for someone ...

This is a workaround for next/previous links not already being in the WP-API response. They're being added, but the syntax isn't final, so I thought in the meantime I would add them myself:

```php
function get_pagination_in_json( $post_response, $post, $context ) {

    // Ensure global post is correctly set
    $old_post = $GLOBALS['post'];
    $GLOBALS['post'] = (object)$post;

    $previous_post = get_adjacent_post( true, '', true, 'foo' );
    $next_post = get_adjacent_post( true, '', false, 'foo' );

    if ( is_a( $previous_post, 'WP_Post' ) ) {
        $previous = get_permalink($previous_post->ID);
        $post_response['pagination']['previous'] = $previous;
    }

    if ( is_a( $next_post, 'WP_Post' ) ) {
        $next = get_permalink($next_post->ID);
        $post_response['pagination']['next'] = $next;
    }

    // Reset global post to its old value
    $GLOBALS['post'] = $old_post;

    return $post_response;
}
add_filter( 'json_prepare_post', 'get_pagination_in_json', 10, 3 );
```

**Comment by amindiary** [comment]
If someone use WP REST API V2, this may help:

adding CFS for custom post type and standard posts (project in my case)
```

function cfs_variables($post_response, $post, $context) {
$post_response->data['CFS']=CFS()->get( false, $post->ID, array( 'format' => 'raw' ) );
  return $post_response ;
}
add_filter('rest_prepare_project', 'cfs_variables', 12, 3);
add_filter('rest_prepare_post', 'cfs_variables', 12, 3);
```

**IMPORTANT:**
True: 
add_filter ('rest_prepare_post' 'function', 12, 3);

False: 
add_filter ('json_prepare_post' 'function', 12, 3); //WRONG

If is Custom Post Type:
add_filter ('rest_prepare_{$post_type}' 'function', 12, 3);

EXAMPLE: Name post type = product; 
add_filter ('rest_prepare_product' 'function', 12, 3);
