### ISSUE TITLE
Feature request: add number field

### ISSUE THREAD

**Issue by kavillock** [mgibbs189/custom-field-suite#263]
as a title, it was be nice to add it

**Comment by mgibbs189** [comment]
Apologies, but I don't see much value in having a separate Number field. The Single-line text field type seems sufficient. Do you have any examples on why this field type is absolutely necessary?

**Comment by chrisvanpatten** [comment]
What if there were an additional field or a filter to allow an HTML5 pattern attribute? I can see there being value in allowing only specific input text in the client-side validation.

For instance if you're building a "price" field, you might want to do something like...

```html
<input type="text" pattern="\d+.\d{2}" title="Price input">
```

It's a little more advanced but it does add some flexibility to the text field.

**Comment by kavillock** [comment]
in html5 we can also add input type number
