### ISSUE TITLE
Date/Time field with timezone support?

### ISSUE THREAD

**Issue by cliffordp** [mgibbs189/custom-field-suite#269]
I read http://customfieldsuite.com/docs/date/ but didn't see a timezone option.

CMB2 has a couple great field types: 
- text_datetime_timestamp_timezone (requires PHP 5.3+)
- select_timezone

Reference: https://github.com/WebDevStudios/CMB2/wiki/Field-Types#types

Does CFS?

**Comment by Colir** [comment]
+1
