### ISSUE TITLE
Only Load Translations in the Admin?

### ISSUE THREAD

**Issue by robneu** [mgibbs189/custom-field-suite#271]
I was wondering, would it make sense to only load the textdomain within the admin to reduce overhead on the front end? Are there any translatable strings on the front end?

If it's possible, do you think it would be a good idea to do an early return if `! is_admin()` in this method? https://github.com/mgibbs189/custom-field-suite/blob/master/cfs.php#L123-L133

**Comment by mgibbs189** [comment]
@robneu yes, that would make a lot of sense.

**Comment by mgibbs189** [comment]
Changes added. Thanks for the suggestion!

**Comment by robneu** [comment]
:+1:
