### ISSUE TITLE
Allow "exclude_from_search" to be TRUE on Related Custom Post types

### ISSUE THREAD

**Issue by brubrant** [mgibbs189/custom-field-suite#272]
I want to be able to remove a CPT from search AND use it as a related CPT to another CPT using relationship field.

More on this:
http://customfieldsuite.com/forums/questions/494/how-can-i-select-custom-post-type-in-cfs-in-order-to-limit-usage-of-cfs-on-such-a-custom-post-type

**Comment by mgibbs189** [comment]
Hey, you can use the `cfs_field_relationship_post_types` filter to choose which posts types to allow.
