### ISSUE TITLE
Bug with rule "IS NOT"

### ISSUE THREAD

**Issue by PafSebastien** [mgibbs189/custom-field-suite#274]
Hi,
I noticed that an error occured when you publish/update a post and one of the rules of the CF uses "IS NOT".

Here's what happens :
`WordPress database error: [You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') OR v.base_field_id IN ())' at line 4]
DELETE v, m FROM wp_cfs_values v LEFT JOIN wp_postmeta m ON m.meta_id = v.meta_id WHERE v.post_id = '108' AND (v.field_id IN () OR v.base_field_id IN ())`

After small investigation, it seems to come from `api.php#654`. I think `$field_ids` is empty, this is why `( )` are empty too in the SQL query.

![capture d ecran 2015-07-30 a 17 13 02](https://cloud.githubusercontent.com/assets/13638441/9088695/b5783f7a-3b91-11e5-8f7e-e7f5d9dcbf30.png)

**Comment by mgibbs189** [comment]
Thanks for reporting. I'm pretty sure this has been fixed either in the latest version (2.4.5) or in the upcoming version (2.5).
