### ISSUE TITLE
Date picker

### ISSUE THREAD

**Issue by Colir** [mgibbs189/custom-field-suite#276]
Hi,
as mention on the doc, the date picker should write the date + a time, something like
 2015-08-18 9:00

http://customfieldsuite.com/docs/date/

But i have only the date : 2015-08-18
not : 2015-08-18 9:00

I can't setup a time

Can you help me ?

thanks

**Comment by mgibbs189** [comment]
The date field does not yet have time support. Closing in favor of #269
