### ISSUE TITLE
Loop fields reordering upon publishing page

### ISSUE THREAD

**Issue by jtomeck** [mgibbs189/custom-field-suite#279]
Hey there,

I tweeted at you, but I'm sure that's not where you want your bugs/issues being discussed. I didn't even think to post here until now, but here it goes:

I'm having a problem where my loop rows are re-ordering when I publish my page. The issue seems to be exactly what was going on in this issue - https://github.com/mgibbs189/custom-field-suite/issues/149.

Was there a solution to this?

If needed, here is the export:
[{"post_title":"Case Studies \/ Featured Work Options","post_name":"case-studies","cfs_fields":[{"id":"9","name":"sj_csfw_client_name","label":"Client Name","type":"text","notes":"","parent_id":0,"weight":0,"options":{"default_value":"","required":"0"}},{"id":"13","name":"sj_cs_intro_summary","label":"Intro Summary","type":"textarea","notes":"","parent_id":0,"weight":1,"options":{"default_value":"","formatting":"auto_br","required":"0"}},{"id":"10","name":"sj_cs_infographic","label":"Main Infographic","type":"file","notes":"","parent_id":0,"weight":2,"options":{"return_value":"url","required":"0"}},{"id":"11","name":"sj_csfw_work","label":"Work","type":"loop","notes":"","parent_id":0,"weight":3,"options":{"row_display":"0","row_label":"Row","button_label":"Add Row","limit_min":"","limit_max":""}},{"id":"12","name":"sj_csfw_work_images","label":"Images","type":"loop","notes":"Add image OR video. DO NOT USE BOTH (If both video and image are uploaded, it will default to displaying the image)","parent_id":11,"weight":4,"options":{"row_display":"0","row_label":"Column","button_label":"Add Column","limit_min":"1","limit_max":"3"}},{"id":"16","name":"sj_csfw_work_column_width","label":"Column Width","type":"select","notes":"","parent_id":12,"weight":5,"options":{"choices":{"full-width":"full-width","half":"half","third":"third","two-thirds":"two-thirds"},"multiple":"0","required":"0"}},{"id":"14","name":"sj_csfw_work_image","label":"Image","type":"file","notes":"Choose image of work. If you want this column to hold a video, do not use this field.","parent_id":12,"weight":6,"options":{"return_value":"url","required":"0"}},{"id":"15","name":"sj_csfw_work_video_vendor","label":"Vimeo or Youtube","type":"select","notes":"Choose where the video you wish to embed is hosted. If you do not wish to upload a video, leave this at \"None\"","parent_id":12,"weight":7,"options":{"choices":{"None":"None","Vimeo":"Vimeo","Youtube":"Youtube"},"multiple":"0","required":"0"}},{"id":"23","name":"sj_csfw_work_video_id","label":"Video ID","type":"text","notes":"Input the ID of the video you wish to display","parent_id":12,"weight":8,"options":{"default_value":"","required":"0"}},{"id":"18","name":"sj_csfw_sidebar_infographics","label":"Sidebar Infographics","type":"loop","notes":"","parent_id":0,"weight":9,"options":{"row_display":"0","row_label":"Infographic","button_label":"Add infographic","limit_min":"","limit_max":""}},{"id":"19","name":"sj_csfw_sidebar_infographic","label":"Infographic","type":"file","notes":"","parent_id":18,"weight":10,"options":{"return_value":"url","required":"0"}},{"id":"20","name":"sj_csfw_content_callout","label":"Content Callout","type":"wysiwyg","notes":"Important content that you would like to call out in the sidebar.","parent_id":0,"weight":11,"options":{"formatting":"default","required":"0"}},{"id":"21","name":"sj_csfw_awards","label":"Awards","type":"loop","notes":"","parent_id":0,"weight":12,"options":{"row_display":"0","row_label":"Award","button_label":"Add Award","limit_min":"","limit_max":""}},{"id":"22","name":"sj_csfw_award","label":"Award","type":"textarea","notes":"","parent_id":21,"weight":13,"options":{"default_value":"","formatting":"auto_br","required":"0"}}],"cfs_rules":{"post_types":{"operator":"==","values":["casestudies","featured-work"]}},"cfs_extras":{"order":"0","context":"normal","hide_editor":"0","gforms":{"form_id":"","post_type":""}}}]

**Comment by mgibbs189** [comment]
Hi, could you try disabling all other plugins to see if the sorting issue still persists?

**Comment by jtomeck** [comment]
Thanks for the reply! I'm actually no longer working with the company I started this project on and don't have access, however they'll still need to fix the issue. I've sent their current developer this post so he can work with you to solve the issue.

**Comment by mgibbs189** [comment]
@jtomeck I still haven't been able to duplicate the issue, unfortunately.

Please re-open if you encounter this issue again.
