### ISSUE TITLE
Dynamic select options generated through cfs_pre_render_ fields not working within loop.

### ISSUE THREAD

**Issue by jayharland** [mgibbs189/custom-field-suite#280]
I've managed to create dynamic select lists using cfs_pre_render_fields and it works great for the most part. However, inside of loops it does not. The cfs_pre_render_fields function works normally but the values are never added to the cloned fields.

Any ideas?

**Comment by roshansachan** [comment]
Hey @jayharland  I am having similar issue. Any progress?

**Comment by jayharland** [comment]
Negative. I haven't gone back and tried since posting this, and I just went back and tried with version 2.5.3 and I'm running into the same problem. Sorry :/

**Comment by mgibbs189** [comment]
Closing, #348 should address this once implemented.
