### ISSUE TITLE
Meta values are sometimes cut off

### ISSUE THREAD

**Issue by swissspidy** [mgibbs189/custom-field-suite#281]
On a client site there's a field called `price` of type `text` in a field group.

On a page, the field value is set to `USD 99.-`. Everything works fine and the value is saved properly in the database.

However, when getting the value, e.g. by using `CFS()->get( 'price' )` only `U` is returned. The rest is cut off somewhere.

I tracked it down to the `get_fields` method. Changing this:

```
$this->assemble_value_array( $field_data, $hierarchy, $field, false, $options );
```

to this:

```
$this->assemble_value_array( $field_data, $prev_hierarchy, $field, false, $options );
```

seemed to do the trick. Unit tests are probably needed to make 100% sure.

**Comment by mgibbs189** [comment]
Thanks for the info. I haven't run into that issue before, but I'll investigate further within the next week or two.

**Comment by mgibbs189** [comment]
@swissspidy Any chance you could export your entire field group (containing the `price` field) into http://gist.github.com and paste the resulting link?

**Comment by swissspidy** [comment]
@mgibbs189 Sure, here it is: https://gist.github.com/swissspidy/b0ab7afa71f4ed74a6e3

The first one is the field in question (`productprice`).

**Comment by mgibbs189** [comment]
Thanks @swissspidy, a couple more questions:

1. Do you have other CFS fields with the name of `productprice` (in another field group)?
2. Are any other text fields having that issue?

**Comment by swissspidy** [comment]
1. No, there's only that one field group set up.
2. Not that I'm aware of.

I'll ask the client again how it currently looks like. Will update to 2.5.1 as well after using a forked version for some time now.

**Comment by swissspidy** [comment]
Note: The issue still exists in 2.5.1
