### ISSUE TITLE
CFS Sessions Table Deleted

### ISSUE THREAD

**Issue by gsteigerwald** [mgibbs189/custom-field-suite#282]
Everything was working fine and I have not modified the database at all. I went onto one of my pages in /wp-admin/ and it is saying that the cfs_sessions table does not exist. I checked the database and that table is in fact not there anymore. The only cfs table that is still there is the cfs_values table. Any idea what happened here and any idea how i can resolve this?

Thanks,
Glenn

![cfs-issue](https://cloud.githubusercontent.com/assets/1772322/9769443/3b28986e-56f8-11e5-8d1c-d42eeeebf2f1.png)

**Comment by mgibbs189** [comment]
Hi Glenn,

The **only** time CFS deletes the `cfs_sessions` table is when the "Reset" button is clicked from within the Tools menu (in which case, it deletes the `cfs_values` table too).

This is very unlikely to be an issue with the plugin. Try talking to your sysadmin.
