### ISSUE TITLE
Placement Column

### ISSUE THREAD

**Issue by richardegil** [mgibbs189/custom-field-suite#286]
Is it possible to display the page/post name instead of or along with the post ID in the admin UI?

**Comment by sean834** [comment]
What part of the UI are you talking about?

**Comment by chrisvanpatten** [comment]
I think he's referencing the list table of registered field groups.

**Comment by mgibbs189** [comment]
Thanks for reporting. I removed the "Placement" column temporarily... it looks pretty bad for field groups with lots of placement rules. Trying to think of a better UI for it...

**Comment by richardegil** [comment]
Sorry for the late reply... was referring to this (see screenshot, red boxes). The post IDs do provide an easy way to quickly associate page placement. That being said, this could get really ugly with long page titles, so I am not sure what the better option is.

http://d.pr/i/1edBf
