### ISSUE TITLE
Latest update broke old 'get' references

### ISSUE THREAD

**Issue by voltronik** [mgibbs189/custom-field-suite#288]
Anything that still uses `$cfs->get()` instead of `CFS()->get()` has broken in the latest (otherwise brilliant) update. 

Caused a bit of a headache. Just a heads-up in case it needs "fixing".

**Comment by mgibbs189** [comment]
Thanks for reporting, @voltronik 

I just pushed a fix to version 2.5. Re-installing should resolve the issue.
