### ISSUE TITLE
Changes to Gravity Forms broken saving? 

### ISSUE THREAD

**Issue by voltronik** [mgibbs189/custom-field-suite#292]
In the latest update, I know you removed the Gravity Forms integration. This is fine however, it may have affected something else. 

I currently use Gravity Forms to populate custom fields created with CFS but since the update, Gravity Forms no longer saves the information into the custom fields. 

Do you know if the two are related or know of a way I can debug to troubleshoot further?

**Comment by mgibbs189** [comment]
@voltronik here's the code in question (third_party.php): https://github.com/mgibbs189/custom-field-suite/commit/f90b9f12a3a37b0124339ff2e19662325e1ce2df?diff=unified

That's how GF data is getting saved into CFS. If needed, we could probably stick that code into a plugin and generalize it.

**Comment by voltronik** [comment]
Ah, ok. So presumably adding that line back in wont just 'make it work'? What need to happen to make it into a plugin?

**Comment by voltronik** [comment]
Can I have some more help with this?
I'm confused why Gravity Forms isn't just saving the data from the from into the custom fields that CFS creates. Is CFS it's own 'version' of custom fields or just allowing a user to create their own WordPress 'default' custom fields? 
Regardless, are you able to help me integrate the code in the link that you posted above?

Thanks,
Jack

**Comment by mgibbs189** [comment]
Hey @voltronik I'm super swamped this week, but I'll see what I can do next week.

**Comment by voltronik** [comment]
Thanks @mgibbs189 :)

**Comment by voltronik** [comment]
Wondered if there was any news on this yet?
