### ISSUE TITLE
Dynamic row title from Select field

### ISSUE THREAD

**Issue by superbiche** [mgibbs189/custom-field-suite#294]
Hi Matt,

When I use the dynamic field in a row, I can't use a Select field as source for the name: it returns Array (seems normal in the first place).

Any chance you could change this? Can do a PR if needed.

Thanks,
Michel

**Comment by mgibbs189** [comment]
This is intentional, but worth revisiting. The dynamic label feature currently only supports text fields.

**Comment by superbiche** [comment]
Made this PR https://github.com/mgibbs189/custom-field-suite/pull/296

**Comment by mgibbs189** [comment]
Merged. Thanks again
