### ISSUE TITLE
Loop Row Title sometimes don't work

### ISSUE THREAD

**Issue by brubrant** [mgibbs189/custom-field-suite#297]
I noticed that if you have a Text field and a Select field inside a Loop field and tries to use the Text field name as Row title it doesn't work.

### Example

If you have something like this:

```
-- Cars (loop)
---- Car name (text)
---- Car color (Select) 
```

And try to use the car's name as Row title it doesn't show up.

**Comment by mgibbs189** [comment]
This is intentional. The label won't appear when a Loop row is first added. The values must first be saved, then the title will (should) appear correctly on the next refresh.

Is that what you're referring to?

**Comment by brubrant** [comment]
Hi Matt. Thanks for your answer.

No, thats is not what I'm referring. It's a specific case, where you have a Select amongst the loop children and try to use another Text field  (thats is inside the loop as well) as a label for the row. 

On that case the label doesn't work.

**Comment by mgibbs189** [comment]
This has been fixed. Thanks for reporting @brubrant
