### ISSUE TITLE
CFS not using Wordpress get_metadata() cache [enhancement]

### ISSUE THREAD

**Issue by superbiche** [mgibbs189/custom-field-suite#298]
OK this one may look weird, so let me explain:

I'm working on a single page website. The budget is really tiny, so I cannot take time to build it with Ajax and all that stuff that could make it lighter.

I have 20 posts/pages/custom post types that must be displayed on this page, 15 of which use CFS fields.

When I use WP get_post_meta(), it calls get_metadata(). This fetches all the object's meta (i.e. post_meta) the first time, caches it, and fetches it from the cache the next time. Quite good for performance in my case (as I use almost all the metadata in one page). But the fields are not hierarchically ordered.

When I use CFS' API, the resulting data is much better organized. But I have to call it for each post, resulting in 20 DB requests only for CFS data.

So, I was wondering if something could be done about this. For now I see two solutions:

1) Take profit of WP's get_post_meta(). The plugin still needs data from cfs_values, but we can avoid JOINing wp_postmeta. Maybe some benchmarking could be done to see if fetching the whole wp_postmeta table is faster than CFS' queries.
2) Implement a CFS->getAll() API method that would load all CFS related meta in a single query.

Do you think this would be relevant? Have other ideas in mind?

Thanks for your time.

**Comment by mgibbs189** [comment]
Hi @superbiche 

If the content doesn't need to be updated real-time, your best bet might be to cache the entire page.

**Comment by superbiche** [comment]
Hi Matt,

It's true. But unfortunately, I have some elements that need to be updated *almost* real-time.

In fact, I was wondering if something could be done to avoid multiple requests. Maybe some kind of CFS->addToGetList() - the name is awkward, I know, I couldn't find better at the moment - or as I said CFS->getAll(), but this would be less efficient as we might not need every custom field.

Actually, this is not such a big deal. More kinda extra-over-enhancement that might not be useful for everyone, but I was just asking.

If you think that could be of any interest in your plugin, please let me know and I'll work on it when I have some free time.

Thanks for your reply.

**Comment by mgibbs189** [comment]
Honestly, this isn't a good fit for CFS core.

What you're asking for does sound cool. I'm just not sure it's worth the extra code bloat, given that it would be a rarely-used feature.

**Comment by superbiche** [comment]
I agree. Maybe writing a CFS plugin/extension would be much more relevant as one could use it only if needed.
As this would save me 38 extra queries, maybe I'll take some time to do this.
Thanks for sharing your opinion.

**Comment by chrisvanpatten** [comment]
@superbiche be sure to share the link if you open source it. I'm curious about something like this too.
