### ISSUE TITLE
Add ability to change what capability type is used for the field groups post type? 

### ISSUE THREAD

**Issue by nicdford** [mgibbs189/custom-field-suite#300]
It would be awesome if a user could easily change what capability they want their users to edit field group items. Are there any alternatives to just overriding it in the plugin?

https://github.com/mgibbs189/custom-field-suite/blob/c58e3542f792a7af53194e1546b11c017c9f566f/includes/init.php#L56

**Comment by mgibbs189** [comment]
Hi @nicdford, this may warrant a new CFS filter. Could you tell me more about your specific use-case? IIRC, Editors and above are allowed to manage Field Groups.

**Comment by nicdford** [comment]
Hey Matt! An option to create a filter to control that would be perfect. In my scenario, I setup all the post types using pods/equivalent and then extend with CFS (specifically the loop field). My goal would be to make it so editors can only edit the content, not control theme specific things like setting up and creating fields. It's just a precaution to make sure the backend is stripped down to only what the editor needs to manage and change their content.

**Comment by mgibbs189** [comment]
Actually, check out WP's `register_post_type_args` filter (wp-includes/post.php). This will allow you to modify CFS' post type without the need for any new filters.

**Comment by nicdford** [comment]
Ah cool! Thank you, I couldn't find anything like that before. Here is some code that worked for me, maybe it can help someone else if they ever stumble across this: 

```
function change_custom_field_suite_default_capability($args, $post_type) {
    if ( $post_type == 'cfs' ) {
		$args['capability_type'] = 'manage_options';
    }

    return $args;
}
add_action( 'register_post_type_args', 'change_custom_field_suite_default_capability', 10, 2 );
```
