### ISSUE TITLE
Implement new taxonomy meta

### ISSUE THREAD

**Issue by jackmcconnell** [mgibbs189/custom-field-suite#306]
Any plans on adding taxonomy meta to the plugin? There is an add-on to CFS that already does this in a non-WP 4.4 way but direct integration into the core plugin would be great!

**Comment by jchristopher** [comment]
Personally I'd love to see this, but if it's going to get tackled it should likely also accommodate User metadata as well.

**Comment by voltronik** [comment]
Agreed.

**Comment by mgibbs189** [comment]
:+1: just need to find the time to build it :)

**Comment by mgibbs189** [comment]
All CFS methods that use `$post_id` will need to be modified to support users / terms.

Same goes for the `wp_cfs_values` table.

Right now, `$post_id` accepts an integer. One idea would be to switch it to accept either an integer for posts, or a string (e.g. user-535, or term-425). Another option would be leave the post ID as-is, but add another "object_type" database column.

```php
echo CFS()->get( 'my_field', 123 ); // post field
echo CFS()->get( 'my_field', 'user-456' ); // user field
echo CFS()->get( 'my_field', 'term-789' ); // term field
```

or

```php
echo CFS()->get( 'my_field', 456, array( 'object_type' => 'user' ) ); // user field
```

**Comment by chrisvanpatten** [comment]
I think the latter is better/clearer, at the expense of terseness… but I think the tradeoff is worth it.

**Comment by voltronik** [comment]
I agree with @chrisvanpatten - I think the latter feels more like a natural progression of the current CFS code.

**Comment by LC43** [comment]
any progress on this?
