### ISSUE TITLE
After updating CFS True_False no longer working

### ISSUE THREAD

**Issue by jayharland** [mgibbs189/custom-field-suite#312]
Hello,

I recently updated CFS to 2.5.3 and on one of my pages I have a list of about 15 check boxes that, depending on the value, display certain objects on the page or not. This was working normally for a long time but today after I updated the page, I noticed all of them are unchecked (and then nothing is displayed on the page). Re-checking them and re-saving the page does nothing, they are just reloaded empty.

Please help... Thanks!

**Comment by jayharland** [comment]
**UPDATE**

I exported the field group, saved the page with it no longer there, imported it  (basically just recreating the fields) and it started saving and displaying again my selections again.

The only pain is that there are 80 something pages that each use this checklist that all need to be redone.

Not sure if it's something that can be addressed, but until I hear back about it I'll avoid updating CFS again.

Thank you for this great plugin though!

**Comment by mgibbs189** [comment]
We haven't touched the True / False field type in ages. Do you remember which version you upgraded **from**?
