### ISSUE TITLE
PHP class autoloading

### ISSUE THREAD

**Issue by szepeviktor** [mgibbs189/custom-field-suite#313]
Good evening!

I've been looking at your plugin and it seems to be higher quality than *popular* custom fields plugins.

Please consider PHP class autoloading as enterprise grade plugins do this all the time.
See this tool to assess how many PHP files are loaded/executed:
https://wordpress.org/plugins/whats-running/

**Comment by szepeviktor** [comment]
For example https://github.com/Yoast/wordpress-seo/blob/trunk/wp-seo-main.php#L33-L69

**Comment by szepeviktor** [comment]
Of course class files need to be cleaned:
https://github.com/mgibbs189/custom-field-suite/blob/master/includes/api.php#L784

**Comment by szepeviktor** [comment]
And maybe separate loading conditions from classes
https://github.com/mgibbs189/custom-field-suite/blob/master/includes/upgrade.php#L11-L14

**Comment by mgibbs189** [comment]
Thanks for your feedback?

Is there a specific reason (aside from it being in "enterprise" plugins) that you think the classes should be auto-loaded?

Since almost every class is used in a given pageload, autoloading doesn't make much sense. All it does is add extra overhead.

**Comment by szepeviktor** [comment]
For example I think field classes should load on the front-end.

**Comment by szepeviktor** [comment]
... and on non-CFS admin pages.

**Comment by szepeviktor** [comment]
Try using this tool: https://wordpress.org/plugins/whats-running/ with
`define ( 'WHATS_RUNNING_HIGHLIGHT', 'plugins/custom-field-suite' );`
