### ISSUE TITLE
CI before something breaks

### ISSUE THREAD

**Issue by szepeviktor** [mgibbs189/custom-field-suite#314]
Please consider using CI (e.g. Travis)
A tool to begin with: http://wp-cli.org/commands/scaffold/plugin-tests/

An example: https://github.com/Yoast/wordpress-seo/blob/trunk/.travis.yml

**Comment by szepeviktor** [comment]
I mean unit tests and functional test.
You must know what it is all about.

**Comment by mgibbs189** [comment]
Who wants to give this a shot? @szepeviktor? @chrisvanpatten? [Beuller](https://www.youtube.com/watch?v=f4zyjLyBp64)?

I think initially it'd be nice to:

* Programmatically create sample content to test all field types, esp. loop fields
* Test `CFS()->get()`
* Test `CFS()->save()`
* Do `CFS()->set()` then `CFS()->get()`, then compare to make sure values are identical
