### ISSUE TITLE
Dynamic Row Label for loop fields

### ISSUE THREAD

**Issue by szepeviktor** [mgibbs189/custom-field-suite#315]
Could we have dynamic `Row Label`-s displaying a field value inside the loop by its name?

For example by putting: `$link` in `Row Label`.

**Comment by mgibbs189** [comment]
See the `Row Label` documentation: http://docs.customfieldsuite.com/field-types/loop.html

**Comment by szepeviktor** [comment]
:smile: So I've suggested an existing feature.
