### ISSUE TITLE
Unsafe MySQL statement

### ISSUE THREAD

**Issue by szepeviktor** [mgibbs189/custom-field-suite#316]
Maybe others are using statement binary log format.
```
mysqld [Warning] Unsafe statement written to the binary log using statement format since BINLOG_FORMAT = STATEMENT.
The statement is unsafe because it uses a LIMIT clause.
This is unsafe because the set of rows included cannot be predicted. Statement: DELETE FROM wp_cfs_sessions WHERE id = '52c61d3132f165ffaaaa0cef08b7f9f6' LIMIT 1
```
https://github.com/mgibbs189/custom-field-suite/blob/master/includes/session.php#L48
(There are other occurrences of `DELETE ... LIMIT 1`.)

Even adding `ORDER BY id` does not help.
https://dev.mysql.com/doc/refman/5.6/en/replication-features-limit.html

**Comment by szepeviktor** [comment]
Could you drop `LIMIT 1`?

**Comment by mgibbs189** [comment]
The `LIMIT 1` is a best practice. It safeguards to prevent unnecessary records from getting deleted.

**Comment by szepeviktor** [comment]
Thank you.
Do you know any solution for this MySQL warning?
Do you also have these warning in your syslog?

**Comment by mgibbs189** [comment]
I haven't seen that error before. Try googling it to see if you get any results.
