### ISSUE TITLE
How to display field value in the loop field type?

### ISSUE THREAD

**Issue by Sally2002hk01** [mgibbs189/custom-field-suite#317]
I cannot use the following code to display my field value in the loop:
<ul class="flexslider"><?php $fields = CFS()->get('my-loop');
foreach ($fields as $field) {echo "<li><a href='".$field[‘my-link’]."'><img src='".$field['my-banner']."' /><br/>".$field['my-desp']."</a></li>"} ?>
</ul>

It is because $fields is empty and it is not an array?
Why?How can I solve this problem? Thanks!!!!

**Comment by mgibbs189** [comment]
This is not the place for support. Closing.
