### ISSUE TITLE
Warning: Cannot use a scalar value as an array in

### ISSUE THREAD

**Issue by anagio** [mgibbs189/custom-field-suite#324]
I'm getting this warning on a staging server which is nearly an identical environment to our production server. The warning is not showing on our production server. Versions of WP and the plugin are all identical between both. What would be causing this? It seems to be happening anytime `CFS->` is ran.

`Warning: Cannot use a scalar value as an array in /nas/content/staging/theme/wp-content/plugins/custom-field-suite/includes/api.php on line 116`

**Comment by mgibbs189** [comment]
99% of the time, this is due to there being 2 fields with the same name on your edit screen.
