### ISSUE TITLE
WP import/export

### ISSUE THREAD

**Issue by chrisvanpatten** [mgibbs189/custom-field-suite#325]
When exporting a post type with CFS data, the post meta is included in the WXR export as expected.

However, when importing to a duplicate site with the same CFS fields (attached to the same post types), the meta isn't mapped to CFS fields. The meta is all included in the import, and visible in the Custom Fields box, but the UI is rendered as empty.

Is this expected, or have I somehow triggered a bug?

**Comment by jchristopher** [comment]
Slightly guessing but I imagine it's because the data doesn't make it to the `wp_cfs_values` table so CFS doesn't *really* know about it after import.

**Comment by mgibbs189** [comment]
@jchristopher exactly!

@chrisvanpatten it's a trade-off we had to make... `wp_cfs_values` makes exporting / importing harder (one-time process), but makes retrieving values a lot faster and more flexible, esp. for relationship and loop fields.

**Comment by chrisvanpatten** [comment]
Might it be possible to hijack the import process and re-save meta into CFS after an import? I imagine that'd need to hook into the WP importer somehow, check meta names to see what maps to CFS fields, then re-save each value or something?

**Comment by mgibbs189** [comment]
I'm sure it is, but I have no idea how :frowning: 

I suppose you could serialize the relevant `cfs_values` and stick it into a custom WXR field...

**Comment by chrisvanpatten** [comment]
Thinking of getting a list of fields from CFS, mapping the field names to imported meta names, reconstructing the field data array, and CFS()->save()'ing that data. Obviously won't be perfect, but it'd be a big start. I'll have to play around with some ideas.
