### ISSUE TITLE
Number Input Type

### ISSUE THREAD

**Issue by tom95** [mgibbs189/custom-field-suite#333]
In order to run queries on custom field values it would be very handy to have a number field type.

**Comment by mgibbs189** [comment]
Thanks for submitting.

Dev note: It might be worth re-using the `Text` field type, and add a new setting for `HTML5 input type`. Possible options: http://html5doctor.com/html5-forms-input-types/#input-types

**Comment by chrisvanpatten** [comment]
https://github.com/vanpattenmedia/cfs-advanced-text-field lets you use the HTML5 number input type!

**Comment by mgibbs189** [comment]
Closing, see #347
