### ISSUE TITLE
CFS is not defined

### ISSUE THREAD

**Issue by aniketbelwalkar** [mgibbs189/custom-field-suite#335]
Hi,

I am using CFS to show fields at front-end but in the console i am getting error CFS is not defined in console and add image buttons does work in this case either. Let me know if you are able to regenerate the same error at your end.
 
![screenshot from 2016-03-25 18 25 10](https://cloud.githubusercontent.com/assets/13411802/14044462/096bb986-f2b7-11e5-9ca9-845075c912df.png)

**Comment by mgibbs189** [comment]
Have you loaded the assets?

```php
CFS()->form->load_assets();
```

Docs: http://docs.customfieldsuite.com/api/form.html

**Comment by aniketbelwalkar** [comment]
Sorry for the late reply. 

Yes have already added CFS()->form->load_assets(); to load the assets required for the plugin to work but the errors where still in the console and the forms won't work.

**Comment by aniketbelwalkar** [comment]
Hi have found the issue behind this problem. Went through your plugins code and got to know that functions head_scripts() and footer_scripts() are hooked upon wp_head and wp_footer. In my case i am using genesis framework on which i have created a child theme. Here wp_head & wp_footer is not being able to be hooked upon. For now have explicitly added do_actions for wp_head & wp_footer to get the scripts loaded.

**Comment by MohannadHamdy** [comment]
I know this is old but I can't seem to get it to work! can I get any help on this please?
