### ISSUE TITLE
Custom fields are displayed only after saving draft/publishing

### ISSUE THREAD

**Issue by pknadella** [mgibbs189/custom-field-suite#336]
Thanks to all who have contributed to this wonderful Plug-in.

My requirement is to add a few custom fields to a particular category, which I have done successfully thanks to the ease of use and documentation this CFS plug-in has to offer.

But unlike in ACF the custom fields are not loading just by selecting the category, I am forced to save the draft or publish to display those custom fields. So, is this just the way this plug-in functions or am I having any installation or implementation issues?

Thanks :)

**Comment by mgibbs189** [comment]
CFS fields load on pageload, not via ajax. There are no immediate plans to change this.
