### ISSUE TITLE
Short post names in select2 field group editor

### ISSUE THREAD

**Issue by chrisvanpatten** [mgibbs189/custom-field-suite#345]
The select2 field group editor requires you to enter 3 or more characters to search, which effectively means you can't bind a field group to a page with a title that contains fewer than 3 characters.

I was just trying to add a field group to a page named "CV", and it wouldn't work until I renamed the page, attached the field group, then reverted the page rename.

**Comment by mgibbs189** [comment]
@chrisvanpatten you and @jchristopher now have push access to the repo 👍
