### ISSUE TITLE
Figure out a better way to advertise / promote 3rd party add-ons

### ISSUE THREAD

**Issue by mgibbs189** [mgibbs189/custom-field-suite#347]
E.g. https://github.com/vanpattenmedia/cfs-advanced-text-field

**Comment by chrisvanpatten** [comment]
And https://github.com/vanpattenmedia/cfs-options-pages!

**Comment by mgibbs189** [comment]
And https://github.com/jchristopher/cfs-options-screens

**Comment by mgibbs189** [comment]
@chrisvanpatten @jchristopher The Tools menu could use some TLC, perhaps this should be part of that.

On `/templates/page_tools.php` -- perhaps we could add a new `3rd Party Plugins` tab to showcase these other plugins (and make it the default)
