### ISSUE TITLE
API get method throws notices on 404 (and possibly other) pages

### ISSUE THREAD

**Issue by robneu** [mgibbs189/custom-field-suite#349]
Right now, the logic in the API's getter assumes that the post global will always be a `WP_Post` object. On 404 pages, it's not, so warnings get thrown for anything that's been globally hooked in the theme using the current post ID.

It looks like you need an `is_object` or `instanceof WP_Post` check in a couple places. If you like, I can throw together a quick PR to fix it up.

**Comment by mgibbs189** [comment]
@robneu Could you paste the exact PHP warnings you've been seeing?

**Comment by robneu** [comment]
`Notice: Trying to get property of non-object in /Users/robertneu/Sites/wpsitecare.dev/wp-content/plugins/custom-field-suite/includes/api.php on line 33`

`Notice: Trying to get property of non-object in /Users/robertneu/Sites/wpsitecare.dev/wp-content/plugins/custom-field-suite/includes/api.php on line 56`

I think something along these lines would take care of it, but there might be a more elegant solution:

```php
    /*
    ================================================================
        Get a field value
    ================================================================
    */
    public function get_field( $field_name, $post_id, $options ) {
        global $post;

        $defaults = array( 'format' => 'api' ); // "api", "input", or "raw"
        $options = array_merge( $defaults, $options );
        $temp_id = $post instanceof WP_Post ? $post->ID : null;
        $post_id = empty( $post_id ) ? $temp_id : (int) $post_id;

        if ( null === $temp_id ) {
            return false;
        }

        // Trigger get_fields if not in cache
        if ( ! isset( $this->cache[ $post_id ][ $options['format'] ][ $field_name ] ) ) {
            $fields = $this->get_fields( $post_id, $options );

            return isset( $fields[ $field_name ] ) ? $fields[ $field_name ] : null;
        }

        return $this->cache[ $post_id ][ $options['format'] ][ $field_name ];
    }
```

**Comment by mgibbs189** [comment]
All set, thanks @robneu

**Comment by robneu** [comment]
💯
