### ISSUE TITLE
Best way to duplicate field groups (for localizations/translations)

### ISSUE THREAD

**Issue by brubrant** [mgibbs189/custom-field-suite#350]
Hi, @mgibbs189 !

I remember a thread on the forum some time ago where you said that CFS didn't have localization in mind and will never have. I'm ok with that, but I used CFS on several websites with polylang.

Supposing I have a page-clientes.php (pt_br) and a field group called Clients Fields, for my multilingual websites I used to follow this approach:

- Duplicate the page template ( page-clients.php - en_us )
- Duplicate the Field Groups (using [this plugin](https://wordpress.org/plugins/duplicate-post/))
- Rename the new copied Field Group
- Change the page where the Field group would show up.

Doing this I kept the same fields on the new Field Group and it worked like I charm. The problem is that now, when I duplicate the Field Group it doesn't come with the field anymore (I think this is due to the fields having real ids now).

So... to the question: Is there an easy way to duplicate a Field Group? I have some Groups with a lot of fields and that would take a lot of time. Besides that I could mistype some field Name (they are not always the one auto-generated after filling the label).

I tried to export and re-import (changing some ids) with no luck... Can you point me the best way to edit the exported JSON in order to accomplish this?

Did I make myself clear?

Thanks in advance!

**Comment by chrisvanpatten** [comment]
Random thought… Have you considered trying a post duplication plugin? IIRC, I've used [this one](https://wordpress.org/plugins/duplicate-post/) and it shows 'duplicate' buttons on the CFS field groups page that might work. Field groups are ultimately just a Custom Post Type, so I think this might work…

**Comment by brubrant** [comment]
Hi @chrisvanpatten ! Thank you for your input. As I described on my post I used this plugin and this used to work. No anymore...

**Comment by chrisvanpatten** [comment]
@brubrant Oops, my bad… that's what I get for not reading in depth :)

**Comment by mgibbs189** [comment]
@brubrant I can't think of an easy way to duplicate field groups, unfortunately. The issue is that you just need to be able to translate the labels and help text, right?
