### ISSUE TITLE
Shortcode to show a custom field

### ISSUE THREAD

**Issue by ESPONI** [mgibbs189/custom-field-suite#352]
Hi!

is it possible to show the value of custom fields in a post? hopefully via Shortcodes.
Bytheway, awesome addon.

Thanks!

**Comment by mgibbs189** [comment]
@ESPONI we don't provide shortcodes in the plugin itself.

You could easily create your own CFS shortcode via WP's [add_shortcode](https://codex.wordpress.org/Function_Reference/add_shortcode) function. It'd just be a wrapper for `CFS()->get()`.
