### ISSUE TITLE
Can't disable required validation on fields

### ISSUE THREAD

**Issue by mattbanks** [mgibbs189/custom-field-suite#353]
Having an issue where I can't disable the Required validation on fields inside loops on a site. I have a number of loop fields with 2-3 text fields inside on a page and all fields were previously required. We need to make 1-2 of those fields in each loop now optional. I unchecked all the boxes and hit Update, but the boxes remain check on page reload and I can't actually disable the validation.

I haven't had a chance to run WP_DEBUG to see if there's any debug output coming down (need to clone the site down from production to local first).

Any ideas what might be causing this?

CFS Version 2.5.5
WordPress 4.5.2
Custom Genesis child theme

**Comment by jchristopher** [comment]
There was an issue introduced when the checkboxes got updated https://github.com/mgibbs189/custom-field-suite/issues/339 it's since been fixed but not released, pulling down the latest from `master` should resolve the issue for the time being!

**Comment by jchristopher** [comment]
Actually the specific fix you're after is https://github.com/mgibbs189/custom-field-suite/commit/a544959c197862426f2fac4056a9d508cc8abeda but they're both related. Updating to `master` will get around it until a new version of CFS is released.

**Comment by chrisvanpatten** [comment]
This should be fixed now; the commit is in the 2.5.6.1 tag. (Is it cool if I close issues?)

**Comment by mgibbs189** [comment]
Yep, closing.
