### ISSUE TITLE
rgba support for color field type

### ISSUE THREAD

**Issue by jared83** [mgibbs189/custom-field-suite#354]
Would be very useful.
Right now each time I need a color with transparency I have to create an additional text field for opacity.
This is very counterproductive.
Regards

**Comment by mgibbs189** [comment]
Good suggestion, I think it'd be great to add an option to choose between HEX or RGBA.

**Comment by chrisvanpatten** [comment]
Another one I can probably tackle… looks easy enough to support RGBA inside minicolors.

Wish HSLA were possible too w/ minicolors, but HSLA don't get no respect 😉

**Comment by mgibbs189** [comment]
@chrisvanpatten you have push access to the repo 🎈 🍰 

You're welcomed to commit, merge, and do whatever else you need. Just please confer with me before making any data integrity changes (e.g. how things are saved to DB).

**Comment by chrisvanpatten** [comment]
@mgibbs189 I can't imagine I'd ever make data integrity changes without a PR, because I'm an idiot who would inevitably break things 😛 Thanks for the clarification though!
