### ISSUE TITLE
Escaping output

### ISSUE THREAD

**Issue by Jeger** [mgibbs189/custom-field-suite#356]
Should there be an option to auto escape output, or by default escaping output?

Atm. you have to do something like this for every field:

`echo esc_html(CFS()->get( 'field_name' ));`

A lot of boilerplate and my guess is that a lot of developers are not doing this at all giving us a lot of insecure websites.

Are there any reasons adding escaping to CFS is not a good idea?

Could be turned of with a global option, pr. field. or pr. field group or as a option to the get method?

**Comment by chrisvanpatten** [comment]
I'm skipping escaping intentionally. I frequently create a "header code" field where clients can input tracking codes, CSS, etc. 

I think encouraging escaping (perhaps in the docs) is good, but I'm not convinced about enforcing it globally. This could break sites that rely on that behaviour, and anyway encouraging late escaping is generally a [good thing](https://vip.wordpress.com/2014/06/20/the-importance-of-escaping-all-the-things/).

**Comment by mgibbs189** [comment]
@Jeger I'll have to agree with @chrisvanpatten on this one...

Have you considered writing your own escaping function? It'd alleviate your boilerplate issues.

```php
function cfs_esc( $field_name ) {
    return esc_html( CFS()->get( $field_name ) );
}
```

**Comment by Jeger** [comment]
@mgibbs189 @chrisvanpatten You make good points, and thanks for the nice article link, a good read!

I still think there is a lot to be said for automatic escaping with an escape hatch on projects that will probably be used by 100s or 1000s of inexperienced developers. The fact is that best practices will not be followed. 

@chrisvanpatten if you use fields that cant be escaped, or should be escaped differently than `esc_html` how many of the fields? 1 in 10? should that require more effort then or the 9 in 10 text fields?

Look at the way React does this and the way they argue that the easiest way should be the safest way. [dangerously set inner html](https://facebook.github.io/react/tips/dangerously-set-inner-html.html)

I know there is a slight difference between this project and React, but i still think its a valid way at looking at things in a more general way.

However i more than understand you reluctance to break backwards compatibility, and yes a small wrapper function does solve the repetitive typing out of `esc_*`. Still, a really interesting discussion! 😄

**Comment by mgibbs189** [comment]
@Jeger I hear your points, but I think sanitization is ultimately the developer's responsibility. It's the same as if developers use `get_post_meta` or other native functions...
