### ISSUE TITLE
Field type tab Page not found 404

### ISSUE THREAD

**Issue by GrilloPress** [mgibbs189/custom-field-suite#358]
Looking through the automated docs on your github pages I went to read about tabs and found a 404.

I went to: [http://docs.customfieldsuite.com/field-types/tab.html](http://docs.customfieldsuite.com/field-types/tab.html) and got the error

Had a quick look through your gh-pages branch and couldn't find the source file for tab.html

**Comment by mgibbs189** [comment]
Done
