### ISSUE TITLE
Brazilian Portuguese Translation news and an addon

### ISSUE THREAD

**Issue by EliaBR** [mgibbs189/custom-field-suite#360]
Hi Matt,

I don't know the best way to be in touch with you, so I'm trying here :)

I'm writing just to let you know that:
- As you already know and pulled here, CFS now has a Brazilian Portuguese Translation;
- I've translated the readme strings files as well, those available at https://translate.wordpress.org/locale/pt-br/default/wp-plugins/custom-field-suite. Who can approve those suggestions? You?
- I've released my first plugin and it's a Custom Field Suite addon that renames the loops with the first textfield value. It's available at https://wordpress.org/plugins/cfs-auto-loop-label/. Hope it helps someone someway (helps me a lot).

Thanks for this WONDERFUL plugin!
Regards,
Felipe Elia
http://felipeelia.com.br/

**Comment by mgibbs189** [comment]
@EliaBR awesome, thank you!

I wish I could wp.org translations, but they don't allow plugin developers to touch translations (even for their own plugins)... 😦 

The Brazilian translation team on wp.org would actually need to approve the translations.
