### ISSUE TITLE
Plugin interfering with "Feed Them Social" plugin 

### ISSUE THREAD

**Issue by tgmad26** [mgibbs189/custom-field-suite#362]
I recently purchased the "Feed Them Social" plugin and noticed that the Revolution Slider Plugin was not working when the FTS plugin was activated. After disabling all plugins and turning them on one by one, I discovered that when the Custom Field Suite plugin is disabled the Revolutions Slider Plugin and the FTS plugin work fine as well as all my other plugins. Can you help?

**Comment by mgibbs189** [comment]
@tgmad26 we unfortunately don't have the capacity to troubleshoot against premium plugins.

My only suggestion would be to look in your browser console. Perhaps there's some javascript errors that's conflicting with one or both plugins.
