### ISSUE TITLE
Field notes as a textarea

### ISSUE THREAD

**Issue by chrisvanpatten** [mgibbs189/custom-field-suite#368]
I have a few fields that need some fairly complex instructions. I'd love if the "notes" field could be a textarea with line breaks, to make these easier to write/manage as an admin (and easier to read for my users).

It's pretty easy to switch the notes field in the field group editor from an `<input>` to a `<textarea>`, but I'm less certain on where to throw an `nl2br`. Ideally the text would be automatically transformed before it gets to the individual fields, so older fields don't need to be updated to support this behaviour. I looked at putting it in `find_input_fields()` but wasn't sure if that was best.

I also noticed that for tabs, the notes text is processed through `esc_html` which would prevent line breaks from working on tab fields. To fix this and make the behaviour more consistent, should _all_ notes get processed through `esc_html`? So it's something like `nl2br(esc_html($field->notes));` across the board?

**Comment by mgibbs189** [comment]
@chrisvanpatten I like the idea (text -> textarea). Currently, the sanitization just happens in `form.php`.

**Comment by chrisvanpatten** [comment]
@mgibbs189 Cool; I can work up a quick PR.

The only potential issue is if a custom field re-implements how they display notes for some reason; they won't get the benefits of the line-breaks without updating their code to include nl2br.

Potentially could make it work with a `__get()` on the field object to tweak how the `notes` value is returned, but that might be a bit complex for this use case.

**Comment by mgibbs189** [comment]
@chrisvanpatten not to throw a wrench in things, but what if we allowed HTML in there?

**Comment by chrisvanpatten** [comment]
Could also add a custom method (`get_notes`) to the field objects, so we have a universal place to customise the way notes are processed. Could encourage fields that re-implement notes to use that method so they get the updates in the future.

(Just thinking out loud… I'll play around!)

**Comment by chrisvanpatten** [comment]
@mgibbs189 I'd be fine with that… maybe we can whitelist a few tags with kses? `a`, `strong`, `em`, `ul`, `ol`, `li`?

**Comment by mgibbs189** [comment]
and `pre`, yeah that sounds good

**Comment by chrisvanpatten** [comment]
Rough plan… not 100% (or even 70%) confident in this; would love feedback:

1. wp_kses on field group save, so it's sanitised pre-DB
2. When fetching field data, copy `notes` property to `notes_raw` which is the raw newline-containing version of the notes field 
3. Change `notes` to be the `wpautop` version of `notes_raw` (needs to be `wpautop` instead of `nl2br` to accommodate `pre` tags and the like)
4. Update field group editor HTML so it puts `notes_raw` in the textarea (inside `esc_textarea`)
5. Update field HTML to replace the current `<p>` wrapper tag with a `<div>`, and update any style things that happen as a result

Am I overthinking this? Underthinking this? Thoughts are much appreciated.

**Comment by mgibbs189** [comment]
On second thought, let's just leave it as non-HTML for now, then just add `nl2br` into form.php :)

**Comment by chrisvanpatten** [comment]
Still in progress w/ this, just have been distracted by other things :)
