### ISSUE TITLE
Issue with saving child pages

### ISSUE THREAD

**Issue by klasver** [mgibbs189/custom-field-suite#369]
Hello,

Since the last two updates of CFS I am facing the issue not being able to update child pages. The Wordpress page save button doesn't work, when clicking and directly scroll after the click I am having a little moment of 'bouncing' effects. There are no console errors or any other error outputs.

I am running a fully updated Wordpress installation with the plugins:

- WPML Multilingual CMS, 
- WPML String Translation, 
- Yoast SEO
- Custom Field Suite

Downgraded CFS back to Version 2.5.3 made everything works fine again.

**Comment by chrisvanpatten** [comment]
One quick idea: Do you have any validation errors being hidden inside a loop field that you are missing? Currently, if you have an error inside a loop field with the row closed, you'll get scrolled to the error but the message itself would be hidden. 

Can you also include an export of the fields on the page where this is happening?

**Comment by klasver** [comment]
Sorry for my late response but I have found the issue, exactly as you said. There is an error in one of the closed loop fields! Thank you so much.

**Comment by chrisvanpatten** [comment]
Thanks @klasver! This is something we are working on in an upcoming version of CFS (PR #363) so I'll go ahead and close this discussion. Appreciate the report though; it's good to know we are solving real UX issues :)
