### ISSUE TITLE
Page password protected displays custom fields

### ISSUE THREAD

**Issue by mcivita** [mgibbs189/custom-field-suite#372]
Hi,
I added your custom fields into my articles (wordpress) and it works.
Now the problem is when i have to protect an article (or page) with password so by using the set password tool of wordpress.
The page or article is protected but with the password field i also see my custom fields that should be visible only when i accessed to the restricted area...
How to fix?
thanks
Bye

**Comment by mgibbs189** [comment]
This is not a bug. See https://codex.wordpress.org/Using_Password_Protection#Protect_Custom_Fields

**Comment by mcivita** [comment]
Agree! Thanks
