### ISSUE TITLE
Remove bootstrap datepicker

### ISSUE THREAD

**Issue by scrobbleme** [mgibbs189/custom-field-suite#374]
Hello,

The included datepacker is incompatible with other plugins (i.e. WooCommerce Germanized) and results in wrong date format result.

Generally the datepicker should be removed and instead just the JQuery UI Datepicker be used, which is already bundled with WordPress:

- jquery-ui-datepicker -> https://developer.wordpress.org/reference/functions/wp_enqueue_script/
- `wp_enqueue_script( 'jquery-ui-datepicker' );`

**Comment by mgibbs189** [comment]
Sorry, but no. Asking to switch the date picker because it's "in the wrong format" is not a good reason. All CFS dates are returned IN YYYY-MM-DD format.

**Comment by scrobbleme** [comment]
I'm asking to change, because WordPress already includes a datepicker, which can and should be used, as it is more compatible and less error prone.

The wrong format was just the way I found it out.

**Comment by mgibbs189** [comment]
Bootstrap Datepicker has a much better UI. It allows users to switch years, months, even decades much more easily. It's more lightweight. We've been using it for years now with zero issues in terms of browser compatibility.

I'm sorry, but we're not switching to UI datepicker.
