### ISSUE TITLE
Masking text fields

### ISSUE THREAD

**Issue by sasimon** [mgibbs189/custom-field-suite#380]
I would love to use this plugin: it allows for nesting of repeating groups. However, it does not have a time field that matches its date field. I am NOT asking for a timepicker. What I would love to see is the ability to apply a mask to the basic Text type. Standard built-in masks might include e-mail addresses, U.S. and Canadian phone numbers (same system), ZIP codes with the possibility of ZIP+4, Canadian/UK postal codes (capital-number-capital-space-number-capital-number), and, of course, time.

**Comment by chrisvanpatten** [comment]
This would be a great feature for a plugin.

FWIW, my [Advanced Text Field](https://github.com/vanpattenmedia/cfs-advanced-text-field) plugin allows you to use HTML5 client-side patterns. Doesn't work in all browsers, and I know pattern validation isn't the same as an input mask, but it might get you a bit closer.

**Comment by sasimon** [comment]
That's EXACTLY what I need. I was using "pattern" and "input mask"
synonymously. I first learned databases in MS Access, where there is no
practical difference between the two.

**Comment by mgibbs189** [comment]
👍 closing!
