### ISSUE TITLE
File upload to save URL is not working

### ISSUE THREAD

**Issue by ceesvandongen** [mgibbs189/custom-field-suite#381]
Hi Matt Gibbs,
I was trying to use your plugin to create a custom field inwhich I could store the URL of an attachement.
I have used for this the field type ‘file upload’ and selected the return value File URL.

The custum field is perfectly showing in editing the post, and I can select a file from the media lib. The problem is that the Save action results in saving the ID of the attachment instead of the file URL.

Could please you look at this possible bug?!

rgrds, Cees van Dongen

**Comment by mgibbs189** [comment]
This is not a bug. All file fields save the attachment ID.

Use `CFS()->get()` to retrieve the URL, NOT `get_post_meta`.
