### ISSUE TITLE
Como mostrar na home.

### ISSUE THREAD

**Issue by felipecrf** [mgibbs189/custom-field-suite#382]
Olá! Como mostrar o campo personalizado na home? Acredito que seja por causa do módulo do tema. Uso o tema newspaper, e não aparece de jeito nenhum, já instalei vários plugins e nada, nem com o campo nativo também não funciona.

Se eu adicionar o código no arquivo php do post, aparece normalmente, exceto na home, que usa um módulo nativo do tema para puxar os blocos.

**Comment by mgibbs189** [comment]
Sorry, this is not a support forum.
