### ISSUE TITLE
Row index

### ISSUE THREAD

**Issue by sasimon** [mgibbs189/custom-field-suite#383]
I understand that I can inject the value of one of the properties of an item in a loop into its row label. That being said, I would like to inject the item's _index_ into the row label. If the index is zero-based, one should be added to it. Can I do this?

**Comment by chrisvanpatten** [comment]
This probably isn't currently possible. I like the idea though, but I would have questions on how re-orders get handled and such.

Out of curiosity, do ACF loop fields have a number on them by default? I believe they do but don't remember for sure…

**Comment by sasimon** [comment]
Every time the order is changed, the UI would update, regenerating the meta
box and thus the indices would never be 1, 0, 2.

**Comment by chrisvanpatten** [comment]
Yes, I guess I mean more from the point before you drop. So for instance, if I have a list of items 1–5, and pick up number 2, would it make sense for the remaining items to be numbered "1, 3, 4, 5" with your cursor still holding 2… _or_ "1, 2, 3, 4" and automatically re-number themselves as you move your cursor…

Anywho, I like the idea. I'll investigate to see how ACF handles it.

**Comment by sasimon** [comment]
The indices would not change until after dropping.

**Comment by mgibbs189** [comment]
This feature will be supported as part of #348, closing.
