### ISSUE TITLE
Sorting items within a loop

### ISSUE THREAD

**Issue by jaredlyvers** [mgibbs189/custom-field-suite#384]
I have created a master loop that contains 1, 2, 3, 4 column text areas and an image slider. However, anytime you try and reorder an item on a page it goes back to the loop order. So for instance, If I wanted an image slider to be the first item on the page and then a 2 column layout I should be able to add main content loop 2 times. The first only containing the image slider and the second containing the 2 column layout. Each time you save the page, the items reorder themselves, placing the image slider at the bottom of the page. The images below show the main loop and the page with the content on it. 

Shouldn't I be able to create as many loops or blocks as I want and order them in anyway I would like?

![content-loop-on-page](https://cloud.githubusercontent.com/assets/1753621/22303524/427ba3f2-e2f9-11e6-9d91-0b3b9f3670c4.png)
![field-group](https://cloud.githubusercontent.com/assets/1753621/22303523/42783d34-e2f9-11e6-8da7-b53f0b5645c8.png)

Thanks,
JL

**Comment by chrisvanpatten** [comment]
This is probably related to #343. I was also trying to do something like this, with nested loops, and running into issues.

**Comment by jaredlyvers** [comment]
I noticed that the above bug didn't seem to have a resolution. Did you ever find anything more or a fix?

**Comment by chrisvanpatten** [comment]
The bug is a bit beyond my skillset, but hopefully @mgibbs189 can find time soon to take a look :)

**Comment by mgibbs189** [comment]
Closing, too similar to #343 :)
