### ISSUE TITLE
Simple problem to solve. Please help me!

### ISSUE THREAD

**Issue by MrMighty** [mgibbs189/custom-field-suite#385]
Hello Folks!
I have simple coding problem and I'm hoping someone to help me out. 

I have created a custom filed with CFS and I called it **tracking_url**
It holds a URL value eg. google.com/?tracking123423423....
 Filed type I set to: hyperlink in the back-end of wordpress.

On the front-end I want to create a button with href the value of tracking_url
I wrote this code but for reason the code is breaking. (not working as I expect to)

`		
						<button class="claim-button">
							<a href="<?php echo CFS()->get( 'tracking_url' ); ?>">Claim Bonus</a>
						</button>`

Maybe it because CFS is returning a hyperlink instead of text. I dont know. Any ideas how to work around this.

**Comment by chrisvanpatten** [comment]
Hi @MrMighty -

If you're using the hyperlink field, the return value is either a full HTML string or an array, depending on the option you choose as the "Output Format". You can find additional info at the [documentation page for the hyperlink field](http://customfieldsuite.com/field-types/hyperlink.html), but to sum up:

If you set it up to output HTML, you could update your code like so:

```php
<button class="claim-button"> <?php echo CFS()->get( 'tracking_url' ); ?> </button>
```

If you set it up to output PHP Array, you could do the following:

```php
<?php $link =  CFS()->get( 'tracking_url' ); ?>
<button class="claim-button"> <a href="<?php echo $link['url']; ?>">Claim Bonus</a> </button>
```

I'd also add that some browsers might not consider it valid to put an `<a>` tag inside a `<button>` tag.

I'm going to close this issue, but if that still doesn't work please come back with additional information (a link to preview this on a live site, CFS version, and the revised code) and I'll reopen the issue and investigate further!
