### ISSUE TITLE
Loop row of other loop rows

### ISSUE THREAD

**Issue by gravyplaya** [mgibbs189/custom-field-suite#387]
![can it edit](https://cloud.githubusercontent.com/assets/756215/22621780/45c3be98-eae0-11e6-8e80-bd4b32689b49.png)
I want to make 2 groups. But one group a selection of the other one. Is this possible or how can I do this? So the bottom drop down has the 2 keys from the top group?
I hope this makes sense.

**Comment by chrisvanpatten** [comment]
I don't think this is possible with the loop field, but you could probably write a custom field addon that would do this. Likely won't be a feature in core, though.
