### ISSUE TITLE
Cannot add another row after 158 row in loop

### ISSUE THREAD

**Issue by karlotito** [mgibbs189/custom-field-suite#391]
After the 158 rows and upon adding another row then updating it. The new row is not save. And there is no error message.

**Comment by karlotito** [comment]
Even I edit the row with a new data the field is not saving the updated field.

**Comment by mgibbs189** [comment]
You may have reached your server's PHP `post_max_size` limit. Try increasing it.

**Comment by karlotito** [comment]
Thanks,

The problem was the max_input_vars. Increase it from 1000 to 3000.
