### ISSUE TITLE
Custom post type templates missing from page templates

### ISSUE THREAD

**Issue by robneu** [mgibbs189/custom-field-suite#392]
I'm not sure if this has been brought up already, but the new core post type templates aren't available in the page templates dropdown. I could have sworn they were at one point... 🤔

**Comment by mgibbs189** [comment]
Core post type templates? 🤔

**Comment by robneu** [comment]
They're a pretty recent addition to core: https://make.wordpress.org/core/2016/11/03/post-type-templates-in-4-7/

I've been using them for a long time now via custom code, but now that they're in core it should be a little easier to integrate with things like CFS. I looked into this a little bit and it looks like it's because of how the page templates vs post type templates are retrieved in core.

I can probably work on a PR this week if you'd be interested in merging it?

**Comment by mgibbs189** [comment]
Sounds good 👍

**Comment by chrisvanpatten** [comment]
I would love this too!

**Comment by andxbes** [comment]
https://github.com/mgibbs189/custom-field-suite/issues/449

works for me . Please add more supports  templates to next relese
