### ISSUE TITLE
Adding class to the output

### ISSUE THREAD

**Issue by MrMighty** [mgibbs189/custom-field-suite#393]
Can I get some help with CFS here. :)
I have the following code: 

`	<?php
				      $tracking_url = CFS()->get( 'tracking_url' );
				      if ( ! empty ( $tracking_url ) ){
				        echo CFS()->get( 'tracking_url' );
				     }
				   ?>`

Everything runs fine but I need to add a class to the output element (tracking_url) (anchor)
Not sure is it possible to do with CFS. Can you please, provide me some tips. 
Thanks in advance :)

I had an idea to use javascript to add class to the output element, but I was unsure about it

**Comment by mgibbs189** [comment]
It looks like there isn't a UI option for adding a class name. In your case, I'd recommend putting your field within another container element, then targeting it that way...

```php
<div class="link-wrap">
    <?php echo CFS()->get(' tracking_url' ); ?>
</div>
```

CSS:
```css
.link-wrap .cfs-hyperlink { /* some styling */ }
```
