### ISSUE TITLE
Aggregate Field Group Data

### ISSUE THREAD

**Issue by skeathy** [mgibbs189/custom-field-suite#394]
Is it possible to aggregate all the data collected for a single field group onto a single page?

Great plugin - Thanks much.

**Comment by mgibbs189** [comment]
For a single post, use `CFS()->get()` to grab all fields for the current post.

For every post, loop through them using WP_Query and run the same `CFS()->get()` for each...

**Comment by skeathy** [comment]
Wow that is very cool. I just created a custom post type and pointed CFS at that. Once I created the archive template for the custom post type it all clicked - sorry for the stupid question.

Thanks for your help!
