### ISSUE TITLE
Write Date Within Loop

### ISSUE THREAD

**Issue by danhanee** [mgibbs189/custom-field-suite#395]
How would I write the datepicker within the loop to output the name of day, month, date, and year?  

I have this so far: 
<?php $fields = CFS()->get('program_schedule');
	                  foreach ($fields as $field) { ?>
	                  <?php echo '<tr>' ?>
	              <?php echo '<td>'.$field['session_title'].'</td>'; ?>
	              <?php echo '<td>'.$field['date'].'</td>'; ?>
	              <?php echo '<td>'.$field['time'].'</td>'; ?>
	                      <?php echo '</tr>' ?>
	                            <?php   }  ?>
Thanks!

**Comment by mgibbs189** [comment]
Apologies @danhanee but this is an issue tracker, not a support forum. Give http://wordpress.stackexchange.com/ a try
