### ISSUE TITLE
Default value for upload field

### ISSUE THREAD

**Issue by chrisvanpatten** [mgibbs189/custom-field-suite#398]
Not sure exactly how this would be accomplished, but I'd love the ability to set a default value in the file upload field.

We're working with a case right now where we want to give the client the ability to change an image for a certain field, but 90% of the time it will use a specific image. If we could set that as the default, they would only need to remove and re-upload the image in certain cases, rather than uploading from scratch every time they create a new post.

**Comment by mgibbs189** [comment]
@chrisvanpatten Could this be done programmatically? E.g. if no file is uploaded, then force `CFS()->get()` to return a specific file?
