### ISSUE TITLE
Add API for prepopulating fields

### ISSUE THREAD

**Issue by strarsis** [mgibbs189/custom-field-suite#403]
It would be great if API could be added that allows prepropulating fields by PHP code 
(in action/filter handler e.g. in a plugin) similar to ACF https://www.advancedcustomfields.com/resources/dynamically-populate-a-select-fields-choices/.

**Comment by mgibbs189** [comment]
There's a `cfs_pre_render_fields` hook that you *might* be able to use to pre-populate a field's choices...

**Comment by strarsis** [comment]
@mgibbs189: Awesome! Would it be also possible to populate the selection possibilities of a relationship field?

**Comment by strarsis** [comment]
@mgibbs189: This doesn't seem to work with a loop field:
```php
add_filter( 'cfs_pre_render_fields', function ($input_fields) {
	foreach ( $input_fields as $input_field_key => $input_field ) {
		if ( 'test' === $input_field->name ) {
      $input_fields[$input_field_key]->value = array(
        array('Test 3', 'Test 4')
      );
      break;
		}
	}
	return $input_fields;
});
````
The original loop field content is still shown on the page.
