### ISSUE TITLE
Making Custom Field Suite compatible with GlotPress

### ISSUE THREAD

**Issue by EliaBR** [mgibbs189/custom-field-suite#406]
Hi! Some time has past since I sent the translation of CFS to Brazilian Portuguese to you. For me this is THE acf alternative and as a CFS enthusiastic and a heavy GlotPress user, I'd love seeing it fully compatible with GlotPress. So, here I am trying to convince you to make this happen. We'd have to go through some steps, but although it can bring some difficulties at the beginning of the process, I think the benefits would pay the effort. 

- [ ] [The plugin text-domain has to match the plugin slug at the repository](https://developer.wordpress.org/plugins/internationalization/how-to-internationalize-your-plugin/#text-domains), so `Text Domain: cfs` would become `Text Domain: custom-field-suite` and all translation functions occurences would have to be changed. Nowadays we translators can edit just the readme file in GlotPress, but not the plugin. Sending the .po/.mo to you doesn't help the translation of readme, so carrying it all to GlotPress would be the only way to unify the translations. I'd like to send a PR to you with those modifications if you want.
- [ ] Making all actual translators into PTEs. Plugin authors can ask GlotPress administrators to make any user a PTE, according to [this link](https://make.wordpress.org/polyglots/handbook/rosetta/theme-plugin-directories/#requesting-new-translation-editors). You'll have to send the WordPress.org usernames, what I imagine can bring some difficulty (mine is @felipeelia), but you don't have to send it all at once, so this isn't a stopper.

I think that is all. After the text domain changing, the actual translation files will be [automatically imported to GlotPress](https://make.wordpress.org/meta/handbook/documentation/translations/) and you'll can remove them. Translators won't lose their credits at all, as you can see in [Contact Form 7 contributors page](https://translate.wordpress.org/projects/wp-plugins/contact-form-7/contributors).

I really hope seeing that happening, count on me for every needed step :)

**Comment by chrisvanpatten** [comment]
This seems like a great idea! In terms of code, is changing the text domain the only requirement?

**Comment by EliaBR** [comment]
Yes it is, @chrisvanpatten! Looking more thoroughly, we could change the `load_textdomain()` function at `includes/init.php` into a single call to `load_plugin_textdomain`, like:
```
function load_textdomain() {
	load_plugin_textdomain( 'cfs', false, 'custom-field-suite/languages' );
}
```
I've tested here with this change and it works well in both scenarios: .mo file in `wp-content/plugins/custom-field-suite/languages` or in `wp-content/languages/plugins`.

**Comment by mgibbs189** [comment]
Given that GlotPress hasn't been updated in 10+ months with ~400 active installs, I'm closing this for now. Not sure what side effects there'd be if we switched the current `text-domain`.

**Comment by EliaBR** [comment]
Hi @mgibbs189, by GlotPress I didn't mean the plugin, I meant the official [WordPress translation plataform](https://translate.wordpress.org/projects/wp-plugins/custom-field-suite), which is GlotPress based. PLEASE, give a deeper look at the importance of changing the translation process to the "official way". I promise to help (I was planning working at this on next holidays) :)
