### ISSUE TITLE
Looking for specific Info about this plugin

### ISSUE THREAD

**Issue by bizactuator** [mgibbs189/custom-field-suite#407]
I need to add 5 custom fields to WP, I am using WooCommerce for Shopping cart on WP.
Want to add it to WP not just WooCommerce, so found this.

I don't need the data to be displayed online, just in the database, and allow the user to edit it on he profile.php page. Does this plugin allow that?
or is it only for data to display on a website?

Thank you much.
Best Regards.
-Rich

**Comment by mgibbs189** [comment]
Sorry, but this is not a support forum.
