### ISSUE TITLE
Duplicating Pods with Custom Field Suite Fields

### ISSUE THREAD

**Issue by azaleas** [mgibbs189/custom-field-suite#410]
CPT created with pods framework is not duplicating custom fields, created with Custom Field Suite, while using duplication plugins like Duplicate Post.

Any ideas, suggestions, recommendations?

Original topic: https://wordpress.org/support/topic/not-working-with-post-duplication-plugins/

**Comment by mgibbs189** [comment]
Suggestion: if you're using Pods for post types, then you should also use it for custom fields as well. It's a great plugin!
