### ISSUE TITLE
Text disappears

### ISSUE THREAD

**Issue by DesignMeCG** [mgibbs189/custom-field-suite#412]
I've have a custom post type with a custom field. Worked fine until I went in to edit some text within the field and all the text is gone ... vanished ... but it still appears on the front end. What's going on??

**Comment by mgibbs189** [comment]
How are you displaying the field value on the front-end? CFS()->get()? Or get_post_meta()?

**Comment by DesignMeCG** [comment]
I had to discontinue use of this plugin and use another because it wouldn't work - it continually dropped the text making it uneditable. I used the CFS method.

**Comment by mgibbs189** [comment]
Probably a compatibility issue w/ another plugin or something, I have yet to reproduce after considerable use / testing. Closing this ticket.

**Comment by DesignMeCG** [comment]
I deactivated all other plugins when I tried using it - even changed themes - still didn't work. Anyway - thanks for getting back to me.
