### ISSUE TITLE
using update_post_meta function

### ISSUE THREAD

**Issue by saxap** [mgibbs189/custom-field-suite#414]
When i try update meta fields by update_post_meta(), my custom filelds created by CFS isn't completing, but native meta fields is compliting instead.
If i complete CFS fields manualy, i got duplicated rows in _postmeta table with same keys.

Did i something wrong?

**Comment by mittyan** [comment]
Same for me here!
I can't update a field via update_post_meta - it doesn't work properly.
Plus I  just noticed - when you update a field via CFS()->save method, even if we set the ID and post_type of the post to be updated in the args array - array( 'ID' => 123, 'post_type' => 'sessions' ) - it won't only update this existed post but create a new one with the default title "My CFS post", at the moment I'm removing 1600 posts were created during the tests: https://gyazo.com/277105b75c1126e77bb9b5888ca48d2a

Full code example:
$field_data_timer = array( 'session_timer' => $_POST['timer'] );
$session_id = array( 'ID' => $_POST['sessionid'], 'post_type' => 'sessions' );
CFS()->save( $field_data_timer, $session_id );

Could you please fix this bug? I'm using your plugin for years, but never created a new post via frontend - that's a really important function that should be fixed.

**Comment by mgibbs189** [comment]
Closing, see https://wordpress.org/support/topic/duplicates-on-cfs-save-update_post_meta-issue/
