### ISSUE TITLE
How to post meta fields data while creating a post using rest api ?

### ISSUE THREAD

**Issue by bhargavgollamudi** [mgibbs189/custom-field-suite#415]
I am using WP rest api code to create a post. In this request i need to also pass CFS meta fields data, How can i send this ? 

Currently i am using create post JSON Array will be like below.

Array
(
    [title] => Pooja Kumar
    [status] => publish
    [cfs_fields] => Array
	(
		[display_in_todays_pic] => 1
		[default_image] => 1616
	)
)

But it is not working.

**Comment by mgibbs189** [comment]
Closing, this is not a support forum.

Docs: http://customfieldsuite.com/api/save.html
