### ISSUE TITLE
Wysiwyg Issue: Keeps on reverting to old version

### ISSUE THREAD

**Issue by ambisyoso901** [mgibbs189/custom-field-suite#425]
![cfs wysiwyg](https://user-images.githubusercontent.com/13127584/37086982-f9d5ce18-2233-11e8-97a8-4ed34621c57f.png)

**Comment by nauweb-dev** [comment]
This is also happening to my websites. @ambisyoso901 did you find any solution for this issue?

I really don't want to downgrade my wordpress to older version.

**Comment by ambisyoso901** [comment]
Hi @nauweb-dev,

Yes, I've found a solution but don't know if it will fixed entirely because there are times it will revert to the same display.

Copy this file to "/plugins/custom-field-suite/assets/js/tinymce"

[code.min.zip](https://github.com/mgibbs189/custom-field-suite/files/1810593/code.min.zip)

I hope this works for you :)

**Comment by jedweb** [comment]
Thanks for the attempted help @ambisyoso901 

Unfortunately it didn't work for me. I have CFS on many sites and can't get the Wysiwyg editor to allow HTML editing. Very frustrating.

**Comment by LinkReloaded** [comment]
Please fix it!!.. i don´t want to change to ACF.... 
CFS is very clean and simple to use. 
:)

**Comment by ambisyoso901** [comment]
@LinkReloaded, and @jedweb 

Try also installing plugin TinyMCE Advanced, this will help also, to render the Wysiwyg issue, just do a hard refresh or do a site cache.

TinyMCE Advanced help me rendered the correct display.

**Comment by sectsect** [comment]
I have same problem.
This problem forced me to downgrade WordPress Core.

It seems that it is not able to load any JS files for TinyMCE.

**Comment by ambisyoso901** [comment]
Try downloading Advanced TinyMCE it will fixed the problem :) and do a hard refresh and re-login your worpdress account again.

**Comment by Hutchington** [comment]
Is there any solution to this? The TinyMCE Advanced didn't solve for me.

**Comment by bemdesign-er** [comment]
We are seeing this issue when the user is not an admin (so editor role and below). Not sure what might be the cause behind it. Admins get the expected editor. Possible conflict between the new WordPress editor experience and TinyMCE? I don't see any JS errors though.
