### ISSUE TITLE
Can't update my page/post - Your Session Expired

### ISSUE THREAD

**Issue by sannyrss** [mgibbs189/custom-field-suite#431]
Hi,

I have created a loop Custom Field and when the size of looping becomes 7/8 it is not updating and when I click publish it shows YOUR SESSION EXPIRED.

Please help how can I fix this issue.

Earlier I thouht this is a Website setting issue and posted it here https://stackoverflow.com/questions/49667287/wordpress-your-session-has-expired-after-i-publish-post but no this is plugin issue as it is happening same in other website. 

Thanks Sanny

**Comment by mgibbs189** [comment]
Sessions expire after **4 hours**. If you've left the tab open for longer than that, then you'll see that error.
