### ISSUE TITLE
Loop fields are hidden by default

### ISSUE THREAD

**Issue by x9t9** [mgibbs189/custom-field-suite#433]
I might be simply doing something very wrong (just installed the plugin 10 min ago ) but -
The loop fields seem to be hidden by default .
When adding a new loop ( with fields ) and accessing the new post UI - the only thing visible is the "add row" button.
I tried to tick the "Show the values by default" - but nothing happened. I also tried adding default values to each field - but still the same,
I have noticed some "eye" icon ( "Toggle row visibility" probably to show those fields ??  )  - but still - nothing. ( only after adding a row does it work )

So either 
1 - something is broken on my particular system ( no other plugins nor themes ) .
2 - I am doing something wrong or
3 - this is intended ?

I am using wp 4.9.5. no plugins nor themes .

**Comment by mgibbs189** [comment]
@x9t9 It's not a bug, no loop rows are added by default. You have to click "Add row" to add one.
