### ISSUE TITLE
how can I generate Field Groups from theme file?

### ISSUE THREAD

**Issue by Faares** [mgibbs189/custom-field-suite#436]
Greeting,
is there a way to write a field group via theme code not UI?
and thanks for your great job 😄

**Comment by chrisvanpatten** [comment]
I haven’t tested this recently but it might still work: https://github.com/TomodomoCo/cfs-require-import

**Comment by Faares** [comment]
I test it, there is an error: `CFS()->field_group` is null, so can't call `import` function.
