### ISSUE TITLE
Custom Validation Message

### ISSUE THREAD

**Issue by umang-metatagg** [mgibbs189/custom-field-suite#438]
Please can you help me to set custom error message for validation. currently, I unable to modify default validation error message.

For example, If i have set maximum 3 items for loop field validation, it show me message as below:

Please select between 0 and 3 items.

I want to set message like this: ""You can add maximum 3 courses in 1 row"

Please can you help me. Thanks!

**Comment by mgibbs189** [comment]
Sorry, but the validation error messages are not customizable at this time.
