### ISSUE TITLE
Allowed memory size and ...

### ISSUE THREAD

**Issue by okegima** [mgibbs189/custom-field-suite#439]
Greeting, am having an issue with the field type select and wordpress + wamp server. 

well to explain, when am using the select on a page editor for exemple, after few update, am having the following php error : Allowed memory size of ... / / ... wp-includes\functions.php on line 5231

after restarting wamp all service, it works again but broke again till few other update. 

Withe some stress test, it apear to happen when plugin like bellow are activated
WooCommerce Version 3.4.3
WP-Optimize Version 2.2.4

If am changing the type by color for exemple, with the over setting activated, and after some stress test, it do not happen. 

am doing this on localhost as i don't want to have trouble on the mutualised server. 

My current setting : 
WordPress 4.9.7 running
Custom Field Suite Version 2.5.12
into my php.ini, memory_limit = 512M
Wamp 3.0.6

Hope my repport could help to fix this issue !

**Comment by mgibbs189** [comment]
Apologies, but we can't help fix server issues.
