### ISSUE TITLE
CFS and protected category

### ISSUE THREAD

**Issue by mcivita** [mgibbs189/custom-field-suite#444]
When i use CFS inside a single post or page it displays the field also if the page/post is protected by the Access Category Password plugin.
Is there a way to avoid this problem?
I added the get() code inside single.php and page.php (child theme).
Works perfectly on all pages and posts but not when i have posts that are part of protected category (Access Category Password)
Can you pls help me?

**Comment by mgibbs189** [comment]
@mcivita CFS does not integrate with `Access Category Password` or any other access control plugins for that matter. You're responsible for wrapping `CFS()->get()` within checks to make sure that the given field(s) are / should be viewable.
