### ISSUE TITLE
Functions Aliases

### ISSUE THREAD

**Issue by robssanches** [mgibbs189/custom-field-suite#450]
I think it would be nice if there were "functions aliases" for the plugins functions.

For example:
`CFS()->get('test');`

It could be written as:
`cfs_get('test');`

This would make code writing much more agile, since it would not use the uppercase letter in the CFS prefix, and would also dispense with the use of ()->.

**Comment by mgibbs189** [comment]
@robssanches Thanks for the suggestion. FYI since `CFS()` is a function, and doesn't need to be uppercase either. `CFS()->get()` and `cfs()->get()` do the same thing

**Comment by robssanches** [comment]
> 
> 
> @robssanches Thanks for the suggestion. FYI since `CFS()` is a function, it doesn't need to be uppercase either. `CFS()->get()` and `cfs()->get()` do the same thing

You're right  @mgibbs189 

But anyway I leave as a suggestion because I believe that `cfs_get()` could be a good alternative to using `cfs()->get()`.
