### ISSUE TITLE
4/2/19 Update causing php notices from Line 132 in api.php

### ISSUE THREAD

**Issue by thenomadicmann** [mgibbs189/custom-field-suite#454]
The changes to line 132 of api.php are causing a lot of PHP notices from both cfs fields and cfs option screens fields.

I fixed this by checking if $field_data[ $hierarchy ] is set. Line 132 becomes:

if ( isset( $field_data[ $hierarchy ] ) && is_array( $field_data[ $hierarchy ] ) ) {

**Comment by mgibbs189** [comment]
Thanks, this is fixed in `master`.

**Comment by adrianwaler** [comment]
@mgibbs189 Modification to:
```

                        if ( ! isset( $field_data[ $hierarchy ] ) ) {
                            $field_data[ $hierarchy ] = array();
                        }

                        $field_data[ $hierarchy ][] = $result->meta_value;
```
caused again problem from #452 because this key exist and it's empty string.
`PHP Fatal error: Uncaught Error: [] operator not supported for strings in /nas/content/live/prod8bbl8de/wp-content/plugins/custom-field-suite/includes/api.php:136`
