### ISSUE TITLE
add alt tag when adding images from media library

### ISSUE THREAD

**Issue by mattbra1155** [mgibbs189/custom-field-suite#460]
Hello, 

I would like to add "alt" tags to images that I add using CFS - but I don't have an idea how :( 

This is working for me for thumbnails on my own custome theme (Wordpress):

`$thumbnail_id = get_post_thumbnail_id( $post->ID );
$alt = get_post_meta($thumbnail_id, '_wp_attachment_image_alt', true);   
the_post_thumbnail('large', ['class' => 'portfolio__image', 'alt' => $alt ]); `

Is there any way to implement it so I can access the 'alt'? 

Regards!

**Comment by herrstrietzel** [comment]
Hi mattbra1155,

You've tried to get the images' meta data by 
'get_post_thumbnail_id( $post->ID );'

This function is related to the native wordpress post thumbnail or "featured image".
It's a predefined type of image/post object. 

If you're actually using a cfs based media upload field, your image data value would be retrieved something like this:

`$thumbnail = cfs()->get('your_cfs_image_field');
`
// respectively when you are fetching cfs data e.g. within a loop with changing post ids

`$thumbnail = cfs()->get('your_cfs_image_field', $current_post_id);
`
By default cfs media fields return the media url (in fact the original full size media file).
But you can easily transform the media url to its ID by:

`$thumbnail_id = attachment_url_to_postid($thumbnail);
`
I strongly recommend to always use IDs as return values as they offer way more flexibility - in particular when it comes to responsive images or migrating websites from local to live server environments.

If you just want to add an post thumbnail - go for the native wordpress functionality. 

Ok, most likely you're aware of this (... ridiculous) default, requiring to manually add basic thumbnail functionality in your theme's function.php

```
//post thumbnails
add_theme_support( 'post-thumbnails' );
```

In a nutshell, your code would rather look something like this:

```
// 1.1 if cfs field returns an ID (recommended)
$thumbnail_id = cfs()->get('your_cfs_image_field');
$thumbnail_alt = get_post_meta($thumbnail_id, '_wp_attachment_image_alt', true); 
$thumbnail_url = wp_get_attachment_image_url($thumbnail_id,'large'); 
```

```
// 1.2 if cfs field returns an URL - retrieve ID from URL to access alt meta data 
$thumbnail = cfs()->get('your_cfs_image_field');
$thumbnail_id = attachment_url_to_postid($thumbnail);
$thumbnail_url = wp_get_attachment_image_url($thumbnail_id,'large'); 
$thumbnail_alt = get_post_meta($thumbnail_id, '_wp_attachment_image_alt', true); 

```
```
// 1.3 native post thumbnail (a.k.a. "featured image")
$thumbnail_id = get_post_thumbnail_id( $post->ID ); 
$thumbnail_url = wp_get_attachment_image_url($thumbnail_id,'large'); 
$thumbnail_alt = get_post_meta($thumbnail_id, '_wp_attachment_image_alt', true); 

```
```
// 2. img output
echo '<img src="'.$thumbnail_url.'" class="portfolio__image" alt="'.$thumbnail_alt.'">';

```

As you can see it's basically not a huge difference between post thumbnails and any other added media items except the way these attachments are associated to a post. (IMHO: the term "post thumbnail" should be replaced by "post image" as it's not restricted to small image dimensions).
Fortunately cfs just takes the native "add media" functionality uploading your media file to the library and adding another post meta field for your file (ID/URL).
Thus, all media upload tweaks, like file name sanitizing or automatic resizing on uploading will work as expected. 

Speaking of media upload tweaks: most likely (depending on your theme) you won't have any alt meta data on upload. But you can of course add or edit them in your media library.
Therefore you might consider adding something like this to your function.php 

**Disclaimer: 
Always test additional filters on a local/testing evironment!!!
Your wordpress setup might have other dependencies by plugins/themes etc.
(even though this code should work flawlessly)** 


```
// 3. automatically add alt meta on upload
function add_img_meta_on_upload( $post_ID ) {
	if ( wp_attachment_is_image( $post_ID ) ) {
		$media_title = get_post( $post_ID )->post_title;
		$media_meta = array(
			'ID' => $post_ID,
			'post_title' => $media_title,
		);
		update_post_meta( $post_ID, '_wp_attachment_image_alt', $media_title );
		wp_update_post( $media_meta );
	} 
}
add_action( 'add_attachment', 'add_img_meta_on_upload' );

```
As you can see it's basically shorter to work with media Ids (so you've already been on the right track) as you need them either way for advanced meta data outputs like alt attibutes or more importantly appropriate image sizes.
