### ISSUE TITLE
JSON REST API Integration Plugin?

### ISSUE THREAD

**Issue by AJB99** [mgibbs189/custom-field-suite#461]
Hi thanks for Custom Field Suite, excellent plugin.

I'm using the REST/JSON API for a project and I can't figure out how to integrate the fields/values from CFS into the API response.

Is there a plugin available similar to `acf-to-rest-api` plugin that's available for Advanced Custom Fields?

Is there a different way to go about achieving this?

Thanks in advance for any help.

**Comment by dingman** [comment]
@mgibbs189 Love your plugin - thank you for it. Any plans to work on this implementation to the JSON API?

**Comment by dingman** [comment]
@AJB99 FYI this piece of code solved it, from another ticket

```
function cfs_variables($post_response, $post, $context) {
        $post_response->data['customfields']=CFS()->get( false, $post->ID, array( 'format' => 'raw' ) );
        return $post_response ;
}
add_filter('rest_prepare_page', 'cfs_variables', 12, 3);
```
via  https://github.com/mgibbs189/custom-field-suite/issues/261
