### ISSUE TITLE
Too many select queries on Relation fields (migrated from WP.org)

### ISSUE THREAD

**Issue by salar90** [mgibbs189/custom-field-suite#464]
There is an issue when I make a field type of relation: On the edit page, it does a seprate `SELECT * FROM wp_posts WHERE id=xxxx LIMIT 1` query for each of the posts that are selectable from the list.
for example if there are 4K posts on your DB, it will make 4K queries causing delay on page and heavy load on server. Also, I don't think selecting all fields (*) is necessary.
you can also trace this by using query monitor plugin.

As we are using CFS on a commercial website, I would be more than appreciative if you provide me an estimated time (or plan) for fixing this.

**Comment by mgibbs189** [comment]
@salar90 Try replacing `includes/fields/relationship.php` with this: https://raw.githubusercontent.com/mgibbs189/custom-field-suite/37aa0b0d954c83368a3b78a7e9ae6e4004c96b07/includes/fields/relationship.php
