### ISSUE TITLE
Major bug: CFS erases data from WC product cross-sells and upsells fields on product save

### ISSUE THREAD

**Issue by GoranRista** [mgibbs189/custom-field-suite#483]
CFS doesn't allow for upsells and cross-sells to be specified in the WooCommerce products (admin), and any existing data in those fields will be erased by CFS when the product is saved.
This has been verified on 2 websites, and the issue was introduced quite some time ago with the CFS update.

**To replicate:**

1. Open an existing WooCommerce product for editing, and go to Product Data->Linked Products.
2. Specify a product in the cross-sell field and in the upsell field.
3. Save the product and open those fields once the page refreshes.
4. The fields will be empty.

**To verify, it is indeed CFS erasing the data:**

1. Run WooCommerce in the Troubleshooting mode with all plugins enabled, except for the CFS
2. While in Troubleshooting mode, Edit a WC product in the manner described earlier by setting a cross-sell and upsell products.
3. Save the product and after the page refreshes, check the fields.
4. The upsell and cross-sell data for the product will be there, and will display website front-end where applicable.

**Double verify via product Export/Import:**

1. Export the product category by going to Products->Export, then select ID, Name, Upsells, Cross-sells as columns to export.
2. Once the exported XML has been downloaded, open it and check the Upsells and Cross-sells columns for the product that was previously edited in the Troubleshooting mode. You will find the fields contain the data entered previously while CFS was disabled.
3. Enter data in Upsells and Cross-sells columns for other products in the XML and save it.
4. Import the edited XML back into WC while matching the fields by going to Products->Import.
5. Open the products which were edited using the XML file and updated via Import to verify that those values exist in Upsells and Cross-sells
6. Disable the Troubleshooting mode so that CFS is active again.
7. Re-save those products that contain Upsell and Cross data while CFS is active.
8. After the page refresh, check the fields to find that the data has been erased by CFS
9. Confirm the data has been erased by Exporting those same products and opening the downloaded XML

This is a major bug of a fantastic plugin that can impact sales for a store and complicate things when doing even the smallest updates to the products.

Please fix this and update the plugin promptly.
Thank you!

**Comment by GoranRista** [comment]
@mgibbs189 Any chance of fixing this bug sometime soon, please?

**Comment by mgibbs189** [comment]
Sorry @GoranRista but we don't have the time or resources to test 3rd party compat.

If you figure out the issue, don't hesitate to open a PR
